/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
-/

/-
We proved that if $p$ and $q$ are primes with $q < p$ and $q \nmid p - 1$, then any group of order $pq$ is cyclic.
-/

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Suppose $p$ and $q$ are primes with $q < p$ and $q$ does not divide $p - 1$. Then any group $G$ of order $pq$ is cyclic.
-/
theorem isCyclic_of_card_pq {p q : ℕ} [Fact p.Prime] [Fact q.Prime] (hqp : q < p) (hdiv : ¬ q ∣ p - 1) (G : Type*) [Group G] [Fintype G] (hG : Fintype.card G = p * q) : IsCyclic G := by
  -- Let $P$ be a Sylow $p$-subgroup of $G$ and $Q$ be a Sylow $q$-subgroup of $G$.
  obtain ⟨P, hP⟩ : ∃ P : Subgroup G, Fintype.card P = p ∧ P.Normal := by
    -- By Sylow's theorems, there exists a unique Sylow $p$-subgroup $P$ of $G$.
    obtain ⟨P, hP⟩ : ∃ P : Sylow p G, ∀ Q : Sylow p G, Q = P := by
      -- By Sylow's theorems, the number of Sylow $p$-subgroups is congruent to $1$ modulo $p$ and divides $q$.
      have h_sylow_p_count : (Nat.card (Sylow p G)) ≡ 1 [MOD p] ∧ (Nat.card (Sylow p G)) ∣ q := by
        have h_sylow_p : Nat.card (Sylow p G) ≡ 1 [MOD p] := by
          exact?;
        have h_sylow_p_div : Nat.card (Sylow p G) ∣ Fintype.card G := by
          -- By Sylow's theorems, the number of Sylow $p$-subgroups is equal to the index of the normalizer of a Sylow $p$-subgroup.
          have h_sylow_p_index : Nat.card (Sylow p G) = Subgroup.index (Subgroup.normalizer (Sylow.toSubgroup (Classical.arbitrary (Sylow p G)))) := by
            exact?;
          convert Subgroup.index_dvd_card ( Subgroup.normalizer ( Classical.arbitrary ( Sylow p G ) |> Sylow.toSubgroup ) );
          rw [ Nat.card_eq_fintype_card ];
        -- Since the number of Sylow $p$-subgroups is congruent to $1 \pmod{p}$, it is coprime with $p$.
        have h_coprime : Nat.gcd (Nat.card (Sylow p G)) p = 1 := by
          simpa using h_sylow_p.gcd_eq;
        exact ⟨ h_sylow_p, ( Nat.Coprime.dvd_of_dvd_mul_left h_coprime <| hG ▸ h_sylow_p_div ) ⟩;
      -- Since $q$ is prime and $p > q$, the only divisor of $q$ that is congruent to $1$ modulo $p$ is $1$ itself.
      have h_unique : Nat.card (Sylow p G) = 1 := by
        rw [ Nat.dvd_prime Fact.out ] at h_sylow_p_count ; aesop;
        rw [ ← Nat.mod_add_div ( Fintype.card ( Sylow p G ) ) p ] at *; simp_all +decide [ Nat.ModEq, Nat.mod_eq_of_lt ] ;
        rcases p with ( _ | _ | p ) <;> simp_all +decide [ Nat.mod_eq_of_lt ];
      exact?;
    -- Since $P$ is the unique Sylow $p$-subgroup, it must be normal.
    have hP_normal : P.Normal := by
      constructor;
      intro n hn g
      have h_conj : g • P = P := by
        exact hP _;
      exact h_conj ▸ Set.mem_smul_set.mpr ⟨ n, hn, rfl ⟩;
    refine' ⟨ P, _, hP_normal ⟩;
    have := P.card_eq_multiplicity;
    simp_all +decide [ Nat.factorization_mul ( Nat.Prime.ne_zero Fact.out ) ( Nat.Prime.ne_zero Fact.out ) ];
    simp +decide [ Nat.Prime.factorization ( Fact.out : Nat.Prime p ), Nat.Prime.factorization ( Fact.out : Nat.Prime q ), hqp.ne' ]
  obtain ⟨Q, hQ⟩ : ∃ Q : Subgroup G, Fintype.card Q = q ∧ Q.Normal := by
    -- By Sylow's theorems, the number of Sylow $q$-subgroups $n_q$ satisfies $n_q \equiv 1 \pmod{q}$ and $n_q \mid p$. Since $q < p$ and $q \nmid p-1$, the only possibility is $n_q = 1$.
    have h_nq : (Nat.card (Sylow q G)) = 1 := by
      -- By Sylow's theorems, the number of Sylow $q$-subgroups $n_q$ satisfies $n_q \equiv 1 \pmod{q}$ and $n_q \mid p$. Since $q < p$ and $q \nmid p-1$, the only possibility is $n_q = 1$. Hence, there is exactly one Sylow $q$-subgroup, which must be normal.
      have h_nq : (Nat.card (Sylow q G)) ≡ 1 [MOD q] ∧ (Nat.card (Sylow q G)) ∣ p := by
        have h_sylow_count : (Nat.card (Sylow q G)) ≡ 1 [MOD q] ∧ (Nat.card (Sylow q G)) ∣ Fintype.card G := by
          bound;
          · exact?;
          · rw [ Nat.card_eq_fintype_card ];
            convert Subgroup.card_quotient_dvd_card ( Subgroup.normalizer ( Sylow.toSubgroup ( Classical.arbitrary ( Sylow q G ) ) ) ) using 1;
            · rw [ Nat.card_eq_fintype_card ];
              exact Fintype.card_congr ( Sylow.equivQuotientNormalizer ( Classical.arbitrary ( Sylow q G ) ) );
            · rw [ Nat.card_eq_fintype_card ];
        aesop;
        exact ( Nat.Coprime.dvd_of_dvd_mul_right ( show Nat.Coprime ( Fintype.card ( Sylow q G ) ) q from Nat.Coprime.symm <| Nat.Prime.coprime_iff_not_dvd ( Fact.out ) |>.2 fun h => by have := Nat.modEq_zero_iff_dvd.mp ( left_1.symm.trans <| Nat.modEq_zero_iff_dvd.mpr h ) ; simp_all +decide [ Nat.ModEq, Nat.mod_eq_of_lt Fact.out ] ) right_1 );
      rw [ Nat.dvd_prime Fact.out ] at h_nq ; aesop;
      exact False.elim ( hdiv ( by rw [ ← Int.natCast_dvd_natCast ] ; simpa [ Nat.cast_sub ( Nat.one_le_iff_ne_zero.mpr <| Nat.Prime.ne_zero Fact.out ) ] using left_1.symm.dvd ) );
    -- Since there is only one Sylow $q$-subgroup, it must be normal.
    obtain ⟨Q, hQ⟩ : ∃ Q : Sylow q G, ∀ R : Sylow q G, R = Q := by
      exact?;
    refine' ⟨ Q.toSubgroup, _, _ ⟩;
    · haveI := Fact.mk ( Fact.out : Nat.Prime q ) ; have := Q.card_eq_multiplicity; aesop;
      rw [ Nat.factorization_mul ] <;> aesop;
      rw [ Nat.factorization_eq_zero_of_not_dvd ( show ¬ q ∣ Fintype.card P from fun h => hdiv <| by have := Nat.prime_dvd_prime_iff_eq this_1.1 ( Fact.out : Nat.Prime ( Fintype.card P ) ) ; aesop ) ] ; simp +decide [ this_1.1.factorization ];
    · constructor;
      intro n hn g;
      have := hQ ( g • Q );
      exact this ▸ Subgroup.mem_map_of_mem _ hn;
  -- Since $P$ and $Q$ are normal subgroups of $G$, their product $PQ$ is also abelian.
  have hPQ_abelian : ∀ x ∈ P, ∀ y ∈ Q, x * y = y * x := by
    intro x hx y hy
    have h_comm : x * y * x⁻¹ * y⁻¹ ∈ P ⊓ Q := by
      exact ⟨ by simpa [ mul_assoc ] using P.mul_mem hx ( hP.2.conj_mem _ ( P.inv_mem hx ) y ), by simpa [ mul_assoc ] using Q.mul_mem ( hQ.2.conj_mem _ hy x ) ( Q.inv_mem hy ) ⟩;
    -- Since $P$ and $Q$ are subgroups of $G$ with orders $p$ and $q$ respectively, and $p$ and $q$ are distinct primes, the intersection $P \cap Q$ must be trivial.
    have h_inter_trivial : Fintype.card (↥(P ⊓ Q)) = 1 := by
      have := Subgroup.card_dvd_of_le ( show P ⊓ Q ≤ P from inf_le_left ) ; ( have := Subgroup.card_dvd_of_le ( show P ⊓ Q ≤ Q from inf_le_right ) ; simp_all +decide [ Nat.dvd_prime ] ; );
      rw [ Nat.dvd_prime ( Fact.out : Nat.Prime p ) ] at * ; rw [ Nat.dvd_prime ( Fact.out : Nat.Prime q ) ] at * ; aesop;
    simp_all +decide [ Fintype.card_eq_one_iff ];
    obtain ⟨ a, ha₁, ha₂ ⟩ := h_inter_trivial; have := ha₂ _ h_comm.1 h_comm.2; simp_all +decide [ mul_inv_eq_iff_eq_mul ] ;
  -- Since $P$ and $Q$ are cyclic groups of orders $p$ and $q$, respectively, and $p$ and $q$ are coprime, $P \times Q$ is cyclic.
  have hPQ_cyclic : ∃ x ∈ P, ∃ y ∈ Q, orderOf x = p ∧ orderOf y = q ∧ x * y = y * x := by
    have hP_cyclic : ∃ x ∈ P, orderOf x = p := by
      have := exists_prime_orderOf_dvd_card p ( by rw [ hP.1 ] );
      aesop
    have hQ_cyclic : ∃ y ∈ Q, orderOf y = q := by
      have := Fact.mk ( show Nat.Prime q from Fact.out ) ; have := exists_prime_orderOf_dvd_card q ( by aesop : q ∣ Fintype.card Q ) ; aesop;
    exact ⟨ hP_cyclic.choose, hP_cyclic.choose_spec.1, hQ_cyclic.choose, hQ_cyclic.choose_spec.1, hP_cyclic.choose_spec.2, hQ_cyclic.choose_spec.2, hPQ_abelian _ hP_cyclic.choose_spec.1 _ hQ_cyclic.choose_spec.1 ⟩;
  obtain ⟨ x, hx, y, hy, hx', hy', hxy ⟩ := hPQ_cyclic;
  have hPQ_cyclic : orderOf (x * y) = p * q := by
    have h_coprime : Nat.gcd (orderOf x) (orderOf y) = 1 := by
      exact hx'.symm ▸ hy'.symm ▸ Nat.coprime_primes ( Fact.out : Nat.Prime p ) ( Fact.out : Nat.Prime q ) |>.2 ( by linarith );
    have h_order_prod : ∀ {a b : G}, a * b = b * a → Nat.gcd (orderOf a) (orderOf b) = 1 → orderOf (a * b) = orderOf a * orderOf b := by
      exact?;
    rw [ h_order_prod hxy h_coprime, hx', hy' ];
  have hPQ_cyclic : ∀ g : G, g ∈ Subgroup.zpowers (x * y) := by
    have hPQ_cyclic : Fintype.card (Subgroup.zpowers (x * y)) = p * q := by
      rw [ Fintype.card_zpowers, hPQ_cyclic ];
    have := Subgroup.card_mul_index ( Subgroup.zpowers ( x * y ) ) ; aesop;
    by_cases h : orderOf x * orderOf y = 0 <;> aesop;
  exact ⟨ x * y, fun g => by obtain ⟨ n, rfl ⟩ := hPQ_cyclic g; exact ⟨ n, rfl ⟩ ⟩
