import Playground.Lagarias.FiniteCertificates

/-!
# The finite Lagarias inequalities through 5040

Generated by `generate_lagarias_certificates.py`. The data are untrusted;
`blocks_checked` verifies every numerical obligation by kernel reduction.
No native-evaluation axiom is used.
-/

namespace LeanEval.NumberTheory.Lagarias.FiniteCertificates

open scoped ArithmeticFunction.sigma

def blocks : List Block := [
  ⟨2, 2, 3, 100635⟩,
  ⟨3, 3, 5, 100951⟩,
  ⟨4, 5, 7, 101153⟩,
  ⟨6, 7, 12, 101409⟩,
  ⟨8, 9, 17, 101574⟩,
  ⟨10, 11, 22, 101693⟩,
  ⟨12, 15, 28, 101785⟩,
  ⟨16, 17, 38, 101921⟩,
  ⟨18, 23, 44, 101974⟩,
  ⟨24, 29, 61, 102097⟩,
  ⟨30, 35, 78, 102187⟩,
  ⟨36, 47, 96, 102257⟩,
  ⟨48, 59, 132, 102363⟩,
  ⟨60, 71, 168, 102440⟩,
  ⟨72, 83, 206, 102501⟩,
  ⟨84, 95, 244, 102551⟩,
  ⟨96, 119, 283, 102592⟩,
  ⟨120, 143, 361, 102660⟩,
  ⟨144, 167, 440, 102714⟩,
  ⟨168, 179, 520, 102757⟩,
  ⟨180, 209, 561, 102777⟩,
  ⟨210, 239, 663, 102819⟩,
  ⟨240, 287, 766, 102855⟩,
  ⟨288, 335, 933, 102902⟩,
  ⟨336, 359, 1102, 102941⟩,
  ⟨360, 419, 1187, 102959⟩,
  ⟨420, 479, 1400, 102996⟩,
  ⟨480, 539, 1616, 103029⟩,
  ⟨540, 599, 1833, 103056⟩,
  ⟨600, 719, 2052, 103081⟩,
  ⟨720, 839, 2492, 103122⟩,
  ⟨840, 959, 2938, 103157⟩,
  ⟨960, 1079, 3386, 103186⟩,
  ⟨1080, 1199, 3837, 103211⟩,
  ⟨1200, 1259, 4290, 103233⟩,
  ⟨1260, 1439, 4519, 103244⟩,
  ⟨1440, 1679, 5205, 103271⟩,
  ⟨1680, 1979, 6128, 103303⟩,
  ⟨1980, 2159, 7287, 103335⟩,
  ⟨2160, 2519, 7989, 103353⟩,
  ⟨2520, 2879, 9396, 103382⟩,
  ⟨2880, 3239, 10814, 103408⟩,
  ⟨3240, 3599, 12239, 103430⟩,
  ⟨3600, 3959, 13668, 103449⟩,
  ⟨3960, 4319, 15107, 103467⟩,
  ⟨4320, 5039, 16550, 103483⟩,
  ⟨5040, 5040, 19444, 103510⟩]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem blocks_checked : verifyBlocks 2 5040 blocks = true := by
  decide +kernel

/-- All exceptional small integers required by the RH-conditional argument. -/
theorem le_bound_of_le_5040 (n : ℕ) (hnpos : 0 < n) (hn : n ≤ 5040) :
    ((σ 1 n : ℕ) : ℝ) ≤ bound n := by
  by_cases h1 : n = 1
  · subst n
    norm_num [bound, harmonic_succ]
  · exact verifyBlocks_sound blocks 2 5040 blocks_checked n (by omega) hn

end LeanEval.NumberTheory.Lagarias.FiniteCertificates
