import Playground.RealIsometry.Basic

/-!
# The Seven Frieze Groups

A frieze group is a discrete subgroup of Isom(ℝ²) whose translation subgroup
is isomorphic to ℤ. There are exactly 7 such groups up to isomorphism.

We place the frieze axis along the x-axis with fundamental period 1.
Each group is defined via `Subgroup.closure` of its standard generators.

## Point group elements

The point group of a frieze group is a subgroup of O(2) that preserves the
x-axis. The possibilities are subgroups of the Klein four-group {I, σH, σV, ρ}:

* `σH` — reflection across the x-axis: (x, y) ↦ (x, −y)
* `σV` — reflection across the y-axis: (x, y) ↦ (−x, y)
* `ρ`  — 180° rotation: (x, y) ↦ (−x, −y)

## The seven groups

| Name | Generators | Description |
|------|-----------|-------------|
| p1   | T | translations only |
| p11m | T, σH | horizontal reflection |
| p11g | γ | glide reflection |
| p2   | T, ρ | 180° rotations |
| p2mm | T, σH, σV | both reflections |
| p2mg | T, ρ, σV' | rotations at lattice points, vertical mirrors shifted |
| p2gm | T, σH, ρ' | horizontal mirrors, rotations shifted |
-/

noncomputable section

namespace Frieze

/-! ### Translation vectors -/

/-- The fundamental translation vector (1, 0). -/
def e₁ : EuclideanSpace ℝ (Fin 2) := EuclideanSpace.single 0 1

/-- The half-period vector (½, 0). -/
def halfE₁ : EuclideanSpace ℝ (Fin 2) := (1/2 : ℝ) • e₁

/-! ### Orthogonal matrices -/

private lemma σH_mem : !![1, 0; 0, (-1 : ℝ)] ∈ Matrix.orthogonalGroup (Fin 2) ℝ := by
  constructor <;> ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_two]

private lemma σV_mem : !![(-1 : ℝ), 0; 0, 1] ∈ Matrix.orthogonalGroup (Fin 2) ℝ := by
  constructor <;> ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_two]

private lemma ρ_mem : !![(-1 : ℝ), 0; 0, -1] ∈ Matrix.orthogonalGroup (Fin 2) ℝ := by
  constructor <;> ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_two]

/-- Horizontal reflection matrix: (x, y) ↦ (x, −y). -/
def σH : Matrix.orthogonalGroup (Fin 2) ℝ := ⟨!![1, 0; 0, -1], σH_mem⟩

/-- Vertical reflection matrix: (x, y) ↦ (−x, y). -/
def σV : Matrix.orthogonalGroup (Fin 2) ℝ := ⟨!![-1, 0; 0, 1], σV_mem⟩

/-- 180° rotation matrix: (x, y) ↦ (−x, −y). -/
def ρ : Matrix.orthogonalGroup (Fin 2) ℝ := ⟨!![-1, 0; 0, -1], ρ_mem⟩

/-! ### Generators as plane isometries -/

/-- Translation by (1, 0). -/
def T : PlaneIsometry := RealIsometry.translation e₁

/-- Horizontal reflection: (x, y) ↦ (x, −y). -/
def reflH : PlaneIsometry := multiplication σH

/-- Vertical reflection about x = 0: (x, y) ↦ (−x, y). -/
def reflV : PlaneIsometry := multiplication σV

/-- 180° rotation about origin: (x, y) ↦ (−x, −y). -/
def rot180 : PlaneIsometry := multiplication ρ

/-- Glide reflection: (x, y) ↦ (x + ½, −y). -/
def glide : PlaneIsometry := standardForm σH halfE₁

/-- Vertical reflection about x = ¼: (x, y) ↦ (−x + ½, y). -/
def reflVHalf : PlaneIsometry := standardForm σV halfE₁

/-- 180° rotation about (¼, 0): (x, y) ↦ (−x + ½, −y). -/
def rot180Half : PlaneIsometry := standardForm ρ halfE₁

/-! ### The seven frieze groups -/

/-- **p1** (hop): translations only. -/
def p1 : Subgroup PlaneIsometry := Subgroup.closure {T}

/-- **p11m** (jump): translations and horizontal reflection. -/
def p11m : Subgroup PlaneIsometry := Subgroup.closure {T, reflH}

/-- **p11g** (sidle): generated by a single glide reflection.
    The square of the glide is the fundamental translation. -/
def p11g : Subgroup PlaneIsometry := Subgroup.closure {glide}

/-- **p2** (spinning hop): translations and 180° rotation about lattice points. -/
def p2 : Subgroup PlaneIsometry := Subgroup.closure {T, rot180}

/-- **p2mm** (spinning jump): translations and reflections in both axes.
    Also contains 180° rotations (as σH ∘ σV). -/
def p2mm : Subgroup PlaneIsometry := Subgroup.closure {T, reflH, reflV}

/-- **p2mg** (spinning sidle): translations, 180° rotation at lattice points,
    and vertical reflections at half-lattice points.
    Contains glide reflections (as ρ ∘ σV') but no pure horizontal reflections. -/
def p2mg : Subgroup PlaneIsometry := Subgroup.closure {T, rot180, reflVHalf}

/-- **p2gm** (step): translations, horizontal reflection, and 180° rotation
    at half-lattice points.
    Contains pure horizontal reflections; rotations only at non-lattice points. -/
def p2gm : Subgroup PlaneIsometry := Subgroup.closure {T, reflH, rot180Half}

/-! ### Containment relationships -/

lemma p1_le_p11m : p1 ≤ p11m :=
  Subgroup.closure_mono (by simp [Set.subset_def])

lemma p1_le_p2 : p1 ≤ p2 :=
  Subgroup.closure_mono (by simp [Set.subset_def])

lemma p11m_le_p2mm : p11m ≤ p2mm :=
  Subgroup.closure_mono (by simp [Set.subset_def])

lemma p2_le_p2mg : p2 ≤ p2mg :=
  Subgroup.closure_mono (by simp [Set.subset_def])

/-! ### Helper lemmas for group isomorphisms -/

private lemma translation_mul (d₁ d₂ : EuclideanSpace ℝ (Fin 2)) :
    RealIsometry.translation d₁ * RealIsometry.translation d₂ =
      RealIsometry.translation (d₁ + d₂) := by
  ext x : 2
  simp only [mul_eq, RealIsometry.comp, Function.comp, RealIsometry.translation]
  abel

private lemma translation_one :
    RealIsometry.translation (0 : EuclideanSpace ℝ (Fin 2)) = 1 := by
  ext x : 2
  simp only [RealIsometry.translation, one_eq, RealIsometry.identity, id, add_zero]

private lemma translation_inv (d : EuclideanSpace ℝ (Fin 2)) :
    (RealIsometry.translation d)⁻¹ = RealIsometry.translation (-d) := by
  apply mul_left_cancel (a := RealIsometry.translation d)
  rw [mul_inv_cancel, translation_mul, add_neg_cancel, translation_one]

private lemma T_pow_nat (n : ℕ) :
    T ^ n = RealIsometry.translation ((n : ℝ) • e₁) := by
  induction n with
  | zero => simp [translation_one]
  | succ k ih =>
    rw [pow_succ, ih, T, translation_mul]
    congr 1; module

private lemma T_zpow (n : ℤ) :
    T ^ n = RealIsometry.translation ((n : ℝ) • e₁) := by
  cases n with
  | ofNat k => exact_mod_cast T_pow_nat k
  | negSucc k =>
    simp only [zpow_negSucc, T_pow_nat, translation_inv]
    congr 1; push_cast; module

private lemma e₁_ne_zero : e₁ ≠ (0 : EuclideanSpace ℝ (Fin 2)) := by
  intro h
  have : ‖e₁‖ = 0 := by rw [h, norm_zero]
  rw [e₁, PiLp.norm_single (p := 2) (β := fun _ : Fin 2 => ℝ)] at this
  norm_num at this

private lemma T_not_isOfFinOrder : ¬IsOfFinOrder T := by
  rw [isOfFinOrder_iff_pow_eq_one]
  push_neg
  intro n hn
  rw [T_pow_nat]
  intro h
  have h0 : (RealIsometry.translation ((n : ℝ) • e₁)).toFun 0 = (1 : PlaneIsometry).toFun 0 :=
    congr_arg (·.toFun 0) h
  simp only [RealIsometry.translation, one_eq, RealIsometry.identity, id, zero_add] at h0
  have hreal : (n : ℝ) = 0 := by
    rcases smul_eq_zero.mp h0 with hr | he
    · exact hr
    · exact absurd he e₁_ne_zero
  exact absurd (Nat.cast_eq_zero.mp hreal) (by omega)

private lemma p1_eq_zpowers : p1 = Subgroup.zpowers T :=
  (Subgroup.zpowers_eq_closure T).symm

/-! ### Group isomorphisms -/

/-- The canonical homomorphism `Multiplicative ℤ →* p1` sending `n` to `T^n`. -/
def intToP1Hom : Multiplicative ℤ →* p1 where
  toFun n := ⟨T ^ Multiplicative.toAdd n, by
    rw [p1_eq_zpowers, Subgroup.mem_zpowers_iff]; exact ⟨_, rfl⟩⟩
  map_one' := Subtype.ext (zpow_zero T)
  map_mul' a b := Subtype.ext (zpow_add T (Multiplicative.toAdd a) (Multiplicative.toAdd b))

private lemma intToP1Hom_bijective : Function.Bijective intToP1Hom := by
  constructor
  · intro a b h
    have h' : T ^ Multiplicative.toAdd a = T ^ Multiplicative.toAdd b :=
      Subtype.ext_iff.mp h
    have inj := (injective_zpow_iff_not_isOfFinOrder (G := PlaneIsometry)).mpr T_not_isOfFinOrder
    exact Multiplicative.toAdd.injective (inj h')
  · intro ⟨g, hg⟩
    rw [p1_eq_zpowers, Subgroup.mem_zpowers_iff] at hg
    obtain ⟨n, rfl⟩ := hg
    exact ⟨Multiplicative.ofAdd n, Subtype.ext rfl⟩

/-- **p1 ≅ ℤ**: the translation-only frieze group is infinite cyclic. -/
noncomputable def p1EquivInt : p1 ≃* Multiplicative ℤ :=
  (MulEquiv.ofBijective intToP1Hom intToP1Hom_bijective).symm

/-- **p11g ≅ ℤ**: the glide-reflection frieze group is infinite cyclic,
    generated by the glide reflection (whose square is the fundamental translation). -/
noncomputable def p11gEquivInt : p11g ≃* Multiplicative ℤ := by
  -- Same structure as p1: glide generates an infinite cyclic group.
  -- glide² = T shows glide has infinite order.
  sorry

/-- **p11m ≅ ℤ × ℤ/2**: horizontal reflection commutes with translation. -/
noncomputable def p11mEquiv : p11m ≃* Multiplicative ℤ × Multiplicative (ZMod 2) := sorry

/-- **p2 ≅ D∞**: the infinite dihedral group. rot180 conjugates T to T⁻¹. -/
noncomputable def p2EquivDihedral : p2 ≃* DihedralGroup 0 := sorry

/-- **p2mm ≅ D∞ × ℤ/2**: reflH commutes with the D∞ generated by T and reflV. -/
noncomputable def p2mmEquiv : p2mm ≃* DihedralGroup 0 × Multiplicative (ZMod 2) := sorry

/-- **p2mg ≅ D∞**: generated by glide (infinite order) and reflVHalf (order 2)
    satisfying the dihedral relation reflVHalf * glide * reflVHalf = glide⁻¹. -/
noncomputable def p2mgEquivDihedral : p2mg ≃* DihedralGroup 0 := sorry

/-- **p2gm ≅ D∞ × ℤ/2**: reflH commutes with the D∞ generated by T and rot180Half. -/
noncomputable def p2gmEquiv : p2gm ≃* DihedralGroup 0 × Multiplicative (ZMod 2) := sorry

end Frieze
