import Playground.RealIsometry.Basic

/-!
# The Seven Frieze Groups

A frieze group is a discrete subgroup of Isom(ℝ²) whose translation subgroup
is isomorphic to ℤ. There are exactly 7 such groups up to isomorphism.

We place the frieze axis along the x-axis with fundamental period 1.
Each group is defined via `Subgroup.closure` of its standard generators.

## Point group elements

The point group of a frieze group is a subgroup of O(2) that preserves the
x-axis. The possibilities are subgroups of the Klein four-group {I, σH, σV, ρ}:

* `σH` — reflection across the x-axis: (x, y) ↦ (x, −y)
* `σV` — reflection across the y-axis: (x, y) ↦ (−x, y)
* `ρ`  — 180° rotation: (x, y) ↦ (−x, −y)

## The seven groups

| Name | Generators | Description |
|------|-----------|-------------|
| p1   | T | translations only |
| p11m | T, σH | horizontal reflection |
| p11g | γ | glide reflection |
| p2   | T, ρ | 180° rotations |
| p2mm | T, σH, σV | both reflections |
| p2mg | T, ρ, σV' | rotations at lattice points, vertical mirrors shifted |
| p2gm | T, σH, ρ' | horizontal mirrors, rotations shifted |
-/

noncomputable section

namespace Frieze

/-! ### Translation vectors -/

/-- The fundamental translation vector (1, 0). -/
def e₁ : EuclideanSpace ℝ (Fin 2) := EuclideanSpace.single 0 1

/-- The half-period vector (½, 0). -/
def halfE₁ : EuclideanSpace ℝ (Fin 2) := (1/2 : ℝ) • e₁

/-! ### Orthogonal matrices -/

private lemma σH_mem : !![1, 0; 0, (-1 : ℝ)] ∈ Matrix.orthogonalGroup (Fin 2) ℝ := by
  constructor <;> ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_two]

private lemma σV_mem : !![(-1 : ℝ), 0; 0, 1] ∈ Matrix.orthogonalGroup (Fin 2) ℝ := by
  constructor <;> ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_two]

private lemma ρ_mem : !![(-1 : ℝ), 0; 0, -1] ∈ Matrix.orthogonalGroup (Fin 2) ℝ := by
  constructor <;> ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_two]

/-- Horizontal reflection matrix: (x, y) ↦ (x, −y). -/
def σH : Matrix.orthogonalGroup (Fin 2) ℝ := ⟨!![1, 0; 0, -1], σH_mem⟩

/-- Vertical reflection matrix: (x, y) ↦ (−x, y). -/
def σV : Matrix.orthogonalGroup (Fin 2) ℝ := ⟨!![-1, 0; 0, 1], σV_mem⟩

/-- 180° rotation matrix: (x, y) ↦ (−x, −y). -/
def ρ : Matrix.orthogonalGroup (Fin 2) ℝ := ⟨!![-1, 0; 0, -1], ρ_mem⟩

/-! ### Generators as plane isometries -/

/-- Translation by (1, 0). -/
def T : PlaneIsometry := RealIsometry.translation e₁

/-- Horizontal reflection: (x, y) ↦ (x, −y). -/
def reflH : PlaneIsometry := multiplication σH

/-- Vertical reflection about x = 0: (x, y) ↦ (−x, y). -/
def reflV : PlaneIsometry := multiplication σV

/-- 180° rotation about origin: (x, y) ↦ (−x, −y). -/
def rot180 : PlaneIsometry := multiplication ρ

/-- Glide reflection: (x, y) ↦ (x + ½, −y). -/
def glide : PlaneIsometry := standardForm σH halfE₁

/-- Vertical reflection about x = ¼: (x, y) ↦ (−x + ½, y). -/
def reflVHalf : PlaneIsometry := standardForm σV halfE₁

/-- 180° rotation about (¼, 0): (x, y) ↦ (−x + ½, −y). -/
def rot180Half : PlaneIsometry := standardForm ρ halfE₁

/-! ### The seven frieze groups -/

/-- **p1** (hop): translations only. -/
def p1 : Subgroup PlaneIsometry := Subgroup.closure {T}

/-- **p11m** (jump): translations and horizontal reflection. -/
def p11m : Subgroup PlaneIsometry := Subgroup.closure {T, reflH}

/-- **p11g** (sidle): generated by a single glide reflection.
    The square of the glide is the fundamental translation. -/
def p11g : Subgroup PlaneIsometry := Subgroup.closure {glide}

/-- **p2** (spinning hop): translations and 180° rotation about lattice points. -/
def p2 : Subgroup PlaneIsometry := Subgroup.closure {T, rot180}

/-- **p2mm** (spinning jump): translations and reflections in both axes.
    Also contains 180° rotations (as σH ∘ σV). -/
def p2mm : Subgroup PlaneIsometry := Subgroup.closure {T, reflH, reflV}

/-- **p2mg** (spinning sidle): translations, 180° rotation at lattice points,
    and vertical reflections at half-lattice points.
    Contains glide reflections (as ρ ∘ σV') but no pure horizontal reflections. -/
def p2mg : Subgroup PlaneIsometry := Subgroup.closure {T, rot180, reflVHalf}

/-- **p2gm** (step): translations, horizontal reflection, and 180° rotation
    at half-lattice points.
    Contains pure horizontal reflections; rotations only at non-lattice points. -/
def p2gm : Subgroup PlaneIsometry := Subgroup.closure {T, reflH, rot180Half}

/-! ### Containment relationships -/

lemma p1_le_p11m : p1 ≤ p11m :=
  Subgroup.closure_mono (by simp [Set.subset_def])

lemma p1_le_p2 : p1 ≤ p2 :=
  Subgroup.closure_mono (by simp [Set.subset_def])

lemma p11m_le_p2mm : p11m ≤ p2mm :=
  Subgroup.closure_mono (by simp [Set.subset_def])

lemma p2_le_p2mg : p2 ≤ p2mg :=
  Subgroup.closure_mono (by simp [Set.subset_def])

end Frieze
