"""Stage 0: Scaffold the Lean project directories and generate root import file."""

import os
import shutil


def scaffold(input_dir: str, project_root: str, chapters: list[int], template_dir: str | None = None) -> None:
    """Create the Lean project skeleton."""
    os.makedirs(project_root, exist_ok=True)

    # Copy Lean project template files (lakefile.toml, lean-toolchain)
    if template_dir is None:
        template_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "lean_project_template")
    for fname in ["lakefile.toml", "lean-toolchain"]:
        src = os.path.join(template_dir, fname)
        dst = os.path.join(project_root, fname)
        if os.path.exists(src) and not os.path.exists(dst):
            shutil.copy2(src, dst)

    # Create directory tree
    dirs = [
        os.path.join(project_root, "Formalization"),
        os.path.join(project_root, "Formalization", "utils"),
        os.path.join(project_root, "natural_language", "raw_data", "theorems_and_defs"),
    ]
    for ch in chapters:
        dirs.append(os.path.join(project_root, "Formalization", "intermediate_files", f"ch{ch}"))
        dirs.append(os.path.join(project_root, "experiments", "auto", f"ch{ch}", "verification"))
        dirs.append(os.path.join(project_root, "experiments", "auto", f"ch{ch}", "verification_fl_statement"))

    for d in dirs:
        os.makedirs(d, exist_ok=True)

    # Copy raw chapter data
    raw_dir = os.path.join(project_root, "natural_language", "raw_data")
    for ch in chapters:
        src = os.path.join(input_dir, f"ch{ch}.txt")
        dst = os.path.join(raw_dir, f"ch{ch}.txt")
        if os.path.exists(src):
            shutil.copy2(src, dst)
        else:
            print(f"WARNING: {src} not found, skipping")

    # Generate Formalization.lean (root import)
    root_lean = os.path.join(project_root, "Formalization.lean")
    lines = [f"import Formalization.ch{ch}" for ch in chapters]
    with open(root_lean, "w") as f:
        f.write("\n".join(lines) + "\n")

    # Create placeholder ch*.lean files
    formalization_dir = os.path.join(project_root, "Formalization")
    for ch in chapters:
        ch_lean = os.path.join(formalization_dir, f"ch{ch}.lean")
        if not os.path.exists(ch_lean):
            with open(ch_lean, "w") as f:
                f.write(f"-- Chapter {ch}: placeholder (will be generated by the pipeline)\n")

    print(f"Scaffolded project with chapters {chapters}")
