#!/usr/bin/env python3
"""Configure this local toolchain's optional indexes without rebuilding Mathlib."""
from pathlib import Path
import os

project = Path(__file__).resolve().parent.parent
bin_dir = project / '.lake/toolchains/lean4/build/release/stage2/bin'
cache = project / '.lake/optimization-cache'
for name in ['search', 'tactics']:
    (cache / name).mkdir(parents=True, exist_ok=True)
lean = bin_dir / 'lean'
with lean.open('rb') as f:
    is_wrapper = f.read(2) == b'#!'
if not is_wrapper:
    lean.replace(bin_dir / 'lean.real')
lean.write_text(f'''#!/bin/sh
# Generated by scripts/install-wrapper.py; indexes are local to this playground.
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
export LEAN_SEARCH_INDEX_CACHE_DIR="${{LEAN_SEARCH_INDEX_CACHE_DIR:-{cache / 'search'}}}"
export LEAN_TACTIC_INDEX_DIR="${{LEAN_TACTIC_INDEX_DIR:-{cache / 'tactics'}}}"
exec "$here/lean.real" "$@"
''')
os.chmod(lean, 0o755)
print(f'Configured index directories for {lean}')
