#!/usr/bin/env python3
"""Generate exact (untrusted) data for Lean's Lagarias finite-range checker.

Usage, from v32/playground:
    python3 generate_lagarias_certificates.py > Playground/Lagarias/FiniteRange.lean

Only the Python standard library is used. No floating-point arithmetic enters
certificate generation. Correctness ultimately comes from the Lean proof, not
from this program or its assertions.
"""
from fractions import Fraction
from math import factorial, isqrt
from typing import List, Tuple

LIMIT = 5040
HARMONIC_DENOMINATOR = 1_000_000
LOG_DENOMINATOR = 100_000
LOG_POWER = 64
EXP_TERMS = 30


def generate() -> List[Tuple[int, int, int, int]]:
    sigma = [0] * (LIMIT + 1)
    floors = [0] * (LIMIT + 1)
    for d in range(1, LIMIT + 1):
        for n in range(d, LIMIT + 1, d):
            sigma[n] += d
        floors[d] = floors[d - 1] + HARMONIC_DENOMINATOR // d

    blocks: List[Tuple[int, int, int, int]] = []
    lo = 2
    while lo <= LIMIT:
        h = Fraction(floors[lo], HARMONIC_DENOMINATOR)
        # LOG_POWER is 2^6. Repeated integer square roots give the exact
        # floor of the 64th root; Lean checks the resulting inequality anew.
        base = (h.numerator * LOG_DENOMINATOR**LOG_POWER) // h.denominator
        for _ in range(6):
            base = isqrt(base)
        b = Fraction(base, LOG_DENOMINATOR)
        logarithm = LOG_POWER * (1 - 1 / b)
        exponential = sum((h**k / factorial(k) for k in range(EXP_TERMS)), Fraction(0))
        lower_bound = h + exponential * logarithm
        upper = lower_bound.numerator // lower_bound.denominator
        if not (b > 0 and b**LOG_POWER <= h and logarithm >= 0 and sigma[lo] <= upper):
            raise RuntimeError(f"No valid certificate at n={lo}")
        hi = lo
        while hi < LIMIT and sigma[hi + 1] <= upper:
            hi += 1
        blocks.append((lo, hi, upper, base))
        lo = hi + 1
    return blocks


def main() -> None:
    blocks = generate()
    print('import Playground.Lagarias.FiniteCertificates')
    print('''
/-!
# The finite Lagarias inequalities through 5040

Generated by `generate_lagarias_certificates.py`. The data are untrusted;
`blocks_checked` verifies every numerical obligation by kernel reduction.
No native-evaluation axiom is used.
-/

namespace LeanEval.NumberTheory.Lagarias.FiniteCertificates

open scoped ArithmeticFunction.sigma

def blocks : List Block := [''')
    for i, (lo, hi, upper, base) in enumerate(blocks):
        suffix = ',' if i + 1 < len(blocks) else ']'
        print(f'  ⟨{lo}, {hi}, {upper}, {base}⟩{suffix}')
    print('''
set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem blocks_checked : verifyBlocks 2 5040 blocks = true := by
  decide

/-- All exceptional small integers required by the RH-conditional argument. -/
theorem le_bound_of_le_5040 (n : ℕ) (hnpos : 0 < n) (hn : n ≤ 5040) :
    ((σ 1 n : ℕ) : ℝ) ≤ bound n := by
  by_cases h1 : n = 1
  · subst n
    norm_num [bound, harmonic_succ]
  · exact verifyBlocks_sound blocks 2 5040 blocks_checked n (by omega) hn

end LeanEval.NumberTheory.Lagarias.FiniteCertificates
''')


if __name__ == '__main__':
    main()
