import Playground.Artin.Chapter_2_3

namespace Artin

variable {G : Type*} [Group G]

-- The defining property of the inverse
lemma inv_eq_iff {a t : G} : a⁻¹ = t ↔ a * t = 1 := by
  constructor
  · rintro rfl
    simp
  intro h
  have h2 := congr(a⁻¹ * $h)
  simp [artinGroupCancel] at h2
  grind


@[simp] lemma inv_one : (1 : G)⁻¹ = 1 := by simp [inv_eq_iff]
@[simp] lemma inv_inv (a : G) : a⁻¹⁻¹ = a := by simp [inv_eq_iff]
lemma mul_inv_rev (a b : G) : (a * b)⁻¹ = b⁻¹ * a⁻¹ := by simp [inv_eq_iff, artinGroupCancel]

private def npow {G} [Group G] (g : G) : ℕ → G
  | 0 => 1
  | k + 1 => (npow g k) * g

instance {G : Type*} [Group G] : Pow G ℕ := ⟨npow⟩

@[simp] lemma pow_zero (g : G) : g ^ 0 = 1 := rfl
lemma pow_succ (g : G) (k : ℕ) : g ^ (k + 1) = g ^ k * g := rfl

@[simp] lemma pow_one (g : G) : g ^ 1 = g := by
  have h := pow_succ g 0
  rw [pow_zero, Group.one_mul] at h
  exact h

lemma pow_succ' (g : G) (n : ℕ) : g ^ (n + 1) = g * g ^ n := by
  induction n with
  | zero => simp
  | succ k IH => conv_lhs => rw [pow_succ, IH, Group.mul_assoc, ← pow_succ]

theorem pow_add (g : G) (m n : ℕ) : g ^ (m + n) = g ^ m * g ^ n := by
  induction n with
  | zero => simp
  | succ k IH => rw [← Nat.add_assoc, pow_succ, pow_succ, IH, Group.mul_assoc]

def zpow (g : G) : ℤ → G
  | Int.ofNat n => g ^ n
  | Int.negSucc n => (g ^ (n + 1))⁻¹

instance : Pow G ℤ := ⟨zpow⟩

@[simp] lemma zpow_ofNat (g : G) (n : ℕ) : g ^ (Int.ofNat n) = g ^ n := rfl
@[simp] lemma zpow_natCast (g : G) (n : ℕ) : g ^ (n : ℤ) = g ^ n := rfl
@[simp] lemma zpow_negSucc (g : G) (n : ℕ) : g ^ (Int.negSucc n) = (g ^ (n + 1))⁻¹ := rfl
@[simp] lemma zpow_zero (g : G) : g ^ (0 : ℤ) = 1 := rfl

lemma zpow_add_one (g : G) : ∀ k : ℤ, g ^ (k + 1) = g ^ k * g
  | Int.ofNat n => by
      rw [show (Int.ofNat n + 1 : ℤ) = Int.ofNat (n + 1) from rfl,
          zpow_ofNat, zpow_ofNat, pow_succ]
  | Int.negSucc 0 => by
      rw [show (Int.negSucc 0 + 1 : ℤ) = Int.ofNat 0 from rfl,
          zpow_ofNat, pow_zero, zpow_negSucc, pow_succ, pow_zero,
          Group.one_mul, Group.inv_mul_cancel]
  | Int.negSucc (k + 1) => by
      rw [show (Int.negSucc (k + 1) + 1 : ℤ) = Int.negSucc k from rfl,
          zpow_negSucc, zpow_negSucc, pow_succ' g (k + 1), mul_inv_rev,
          Group.mul_assoc]
      simp

lemma zpow_sub_one (g : G) (k : ℤ) : g ^ (k - 1) = g ^ k * g⁻¹ := by
  have h : g ^ (k - 1) * g = g ^ k := by
    rw [← zpow_add_one]
    congr 1
    omega
  calc g ^ (k - 1) = g ^ (k - 1) * g * g⁻¹ := by
        rw [Group.mul_assoc, Group.mul_inv_cancel, Group.mul_one]
    _ = g ^ k * g⁻¹ := by rw [h]

@[push]
theorem zpow_add (g : G) (m n : ℤ) : g ^ (m + n) = g ^ m * g ^ n := by
  induction n using Int.induction_on with
  | zero => simp
  | succ k IH =>
      rw [← Int.add_assoc, zpow_add_one, zpow_add_one, IH, Group.mul_assoc]
  | pred k IH =>
      rw [show m + (-(k : ℤ) - 1) = (m + -(k : ℤ)) - 1 by omega,
          zpow_sub_one, zpow_sub_one, IH, Group.mul_assoc]

@[push, push ←] theorem zpow_neg (g : G) (n : ℤ) : g ^ (-n) = (g ^ n)⁻¹ := by
  symm
  rw [inv_eq_iff, ← zpow_add, show n + (-n) = 0 by omega, zpow_zero]

/-- The subgroup generated by a single element x, denoted ⟨x⟩ -/
def cyclicSubgroup (g : G) : Subgroup G where
  carrier := { g^k | k : ℤ }
  one_mem := ⟨0, zpow_zero g⟩
  mul_mem := by rintro _ _ ⟨a, rfl⟩ ⟨b, rfl⟩; exact ⟨a + b, zpow_add g a b⟩
  inv_mem := by rintro _ ⟨a, rfl⟩; exact ⟨-a, zpow_neg g a⟩
notation "⟪" x "⟫" => cyclicSubgroup x

lemma mem_cyclicSubgroup_iff (r g : G) : g ∈ ⟪r⟫.carrier ↔ ∃ k : ℤ, r^k = g := by rfl

/- Proposition 2.4.2a - the set of indices k such that x^k=1 -/
def annihilatingIndices (g : G) : AddSubgroup ℤ where
  carrier := { k | g ^ k = 1 }
  zero_mem := zpow_zero g
  add_mem := by
    simp only [Set.mem_setOf_eq]
    intro x y hx hy
    push _ ^ _
    simp_all
  neg_mem := by
    simp only [Set.mem_setOf_eq]
    intro x h
    push _ ^ _
    simp [h]
notation "ℤᵒ("x")" => annihilatingIndices x

@[simp] lemma mem_annihilatingIndices_iff (x : G) (k : ℤ) : k ∈ ℤᵒ(x).carrier ↔ x ^ k = 1 := by rfl

/- Proposition 2.4.2b -/
lemma zpow_eq_zpow_iff (x : G) (r s : ℤ) : x^r = x^s ↔ x^(r-s) = 1 := by
  constructor
  · intro h
    have := congr($h * x^(-s))
    nth_rw 2 [show x ^ (-s) = (x ^ s)⁻¹ by push _ ^ _; rfl] at this
    simp only [Group.mul_inv_cancel] at this
    pull _ ^ _ at this
    grind
  · intro h
    have := congr($h*x^s)
    simp only [Group.one_mul] at this
    rw [show r - s = r + (-s) by lia] at this
    push _ ^ _ at this
    rw [Group.mul_assoc] at this
    simp_all

lemma npow_eq_npow_iff (x : G) (r s : ℕ) (h : s < r) : x^r = x^s ↔ x^(r-s) = 1 := by
  rw [← zpow_ofNat, ← zpow_ofNat, zpow_eq_zpow_iff]
  simp only [Int.ofNat_eq_natCast]
  rw [show (r : ℤ) - ↑s = ↑(r - s) by grind]
  rw [zpow_natCast]

@[push, push ←]
lemma zpow_npow_eq_pow_mul (x : G) (r : ℤ) (s : ℕ) : (x^r)^s = x^(r*s) := by
  induction s with
  | zero => simp
  | succ k IH =>
    rw [pow_succ, IH]
    pull _ ^ _
    grind

lemma zpow_zpow_eq_pow_mul (x : G) (r : ℤ) : ∀ s : ℤ, (x^r)^s = x^(r*s)
  | Int.ofNat n => zpow_npow_eq_pow_mul x r n
  | Int.negSucc n => by
    rw [zpow_negSucc]
    rw [← zpow_natCast]
    pull _ ^ _
    norm_cast
    simp only [zpow_negSucc, pow_succ]
    rw [show Int.negSucc n = -(n + 1) by omega]
    rw [show  x ^ (r * -(↑n + 1)) = x^(-(r * (↑n + 1))) by grind]
    rw [zpow_neg]
    congr
    rw [zpow_npow_eq_pow_mul]
    pull _ ^ _
    grind

/- Proposition 2.4.3 - the order of an element -/
noncomputable def order (x : G) : ℕ := generator ℤᵒ(x)

lemma zpow_order_eq_one (x : G) (r : ℤ) : (x^r)^(order x) = 1 := by
  rw [order, zpow_npow_eq_pow_mul, ← mem_annihilatingIndices_iff]
  grind [multiples_closed, generator_mem]

@[simp] lemma zpow_order_eq_one' (x : G) : x^(order x) = 1 := by
  have := zpow_order_eq_one x 1
  rw [show (1 : ℤ) = Int.ofNat 1 by rfl] at this
  rw [zpow_ofNat] at this
  simp_all

@[simp] lemma zpow_one (x : G) : x^(1 : ℤ) = x := by
  rw [show (1 : ℤ) = Int.ofNat 1 by rfl]
  rw [zpow_ofNat]
  simp

@[simp] lemma one_npow (n : ℕ) : (1 : G)^n = 1 := by
  induction n with
  | zero => simp
  | succ k IH => rw [pow_succ, IH, Group.one_mul]

@[simp] lemma one_zpow : ∀ q : ℤ, (1 : G)^q = 1
  | Int.ofNat n => by simp
  | Int.negSucc n => by simp [zpow_negSucc]

lemma order_1_iff (x : G) : order x = 1 ↔ x = 1 := by
  constructor
  · intro h
    have := zpow_order_eq_one x 1
    simp_all
  · rintro rfl
    rw [order]
    rw [generator_eq_one]
    ext i
    simp [AddGroup.top]

lemma annihilatingSubgroup_eq_multiplesOf (x : G) : ℤᵒ(x) = ℤ(order x) := (generator_eq_iff ℤᵒ(x) (order x)).mp rfl

lemma neq_one_of_lt (x : G) (k : ℤ) (h1 : 0 < k) (h2 : k < order x) : x^k ≠ 1 := by
  intro h
  rw [← mem_annihilatingIndices_iff] at h
  rw [annihilatingSubgroup_eq_multiplesOf] at h
  rw [Artin.zmem_multiplesOf_iff] at h
  lift k to ℕ using (by grind)
  norm_cast at *
  grind [Nat.eq_zero_of_dvd_of_lt h h2]

lemma neq_one_of_lt' (x : G) (k : ℕ) (h1 : 0 < k) (h2 : k < order x) : x^k ≠ 1 := by
  have := neq_one_of_lt x (k : ℤ) (by grind) (by grind)
  simp at this
  grind

/- The set {x^0, x^1, ..., x^(order(x)-1)}
The main content of 2.4.2c is that this set is exactly ⟨x⟩
In a more integrated math library, we might define a function (ZMod n) ↦ G by k ↦ g^k
-/
def powers (x : G) : Set G := (fun k => x ^ k) '' Set.Ico (0 : ℤ) (order x)

lemma mem_powers_iff (x : G) (k : ℤ) : (x ^ k ∈ powers x) ↔ ∃ t : ℕ, t < order x ∧ x ^ k = x ^ t := by
  simp only [powers, Set.mem_image, Set.mem_Ico]
  constructor
  · rintro ⟨ t, ⟨ h1, h2 ⟩, h3 ⟩
    lift t to ℕ using h1
    use t
    norm_cast at *
    simp at h3
    grind
  · rintro ⟨ t, h1, h2 ⟩
    use t
    simp
    grind

lemma mem_powers_iff' (x : G) (k : ℕ) : (x ^ k ∈ powers x) ↔ ∃ t : ℕ, t < order x ∧ x ^ k = x ^ t := by
  simp only [powers, Set.mem_image, Set.mem_Ico]
  constructor
  · rintro ⟨ t, ⟨ h1, h2 ⟩, h3 ⟩
    lift t to ℕ using h1
    use t
    norm_cast at *
    simp at h3
    grind
  · rintro ⟨ t, h1, h2 ⟩
    use t
    simp
    grind

lemma cyclicSubgroup_subset_powers (x : G) (h : 0 < order x) : ⟪x⟫.carrier ⊆ powers x := by
  intro gn hgn
  obtain ⟨ k, hk, rfl ⟩ := hgn
  obtain ⟨ q, r, rfl, h2 ⟩ := exists_quotient_remainder k (order x) (by positivity)
  push _ ^ _
  rw [← zpow_zpow_eq_pow_mul]
  simp
  grind [mem_powers_iff']

lemma powers_subset_cyclicSubgroup (x : G) : powers x ⊆ (cyclicSubgroup x).carrier := by
  intro gn hgn
  obtain ⟨ t, ht, rfl ⟩ := hgn
  use t

/- Proposition 2.4.2c -/
lemma cyclicSubgroup_eq_powers (x : G) (h : 0 < order x) : (cyclicSubgroup x).carrier = powers x := by
  grind [cyclicSubgroup_subset_powers, powers_subset_cyclicSubgroup]

lemma one_step (x : G) : (powers x).ncard = (Set.Ico (0 : ℤ) (order x)).ncard := by
  apply Set.InjOn.ncard_image
  intro a ha b hb h
  simp only [Set.mem_Ico] at h ha hb
  lift a to ℕ using (by grind)
  lift b to ℕ using (by grind)
  simp only [Nat.cast_nonneg, Nat.cast_lt, true_and, zpow_natCast, Nat.cast_inj] at *
  wlog a_le_b : a ≤ b
  · grind [this x b a (by grind) (by grind) (by grind)]
  symm at h
  by_contra h'
  rw [npow_eq_npow_iff _ _ _ (by grind)] at h
  have b_sub_a_lt_order : b - a < order x := by grind
  have := neq_one_of_lt' x (b - a) (by grind) (by grind)
  grind

/- The ℤ analogue of mathlib's `Set.ncard_Ico_nat` -/
@[simp] lemma ncard_Ico_int (a b : ℤ) : (Set.Ico a b).ncard = (b - a).toNat := by
  rw [← Finset.coe_Ico, Set.ncard_coe_finset, Int.card_Ico]

lemma powers_ncard (x : G) : (powers x).ncard = order x := by
  rw [one_step]
  rw [ncard_Ico_int]
  simp

@[simp] lemma zpow_1 (g : G) : g ^ (1 : ℤ) = g := by
  rw [show (1 : ℤ) = Int.ofNat 1 by rfl]
  rw [zpow_ofNat]
  simp

def IsGenerator (r : G) : Prop := ∀ g : G, ∃ n : ℤ, r ^ n = g

lemma generates_iff_cyclicSubgroup (r : G) : IsGenerator r ↔ (cyclicSubgroup r).carrier = Set.univ := by
  constructor
  · intro h
    ext g
    simp only [Set.mem_univ, iff_true]
    obtain ⟨ n, hn ⟩ := h g
    use n
  · intro h g
    have : g ∈ Set.univ := by simp
    rw [← h] at this
    rw [mem_cyclicSubgroup_iff] at this
    obtain ⟨ k, hk ⟩ := this
    use k

inductive K4 : Type
  | one
  | a
  | b
  | c
  deriving Fintype, DecidableEq

instance : Mul K4 where
  mul r s :=
    match r, s with
    | .one, s => s
    | s, .one => s
    | .a, .a => .one
    | .b, .b => .one
    | .c, .c => .one
    | .a, .b => .c
    | .b, .a => .c
    | .a, .c => .b
    | .c, .a => .b
    | .b, .c => .a
    | .c, .b => .a

instance : One K4 where
  one := .one

instance : Inv K4 where
  inv r :=
    match r with
    | .one => .one
    | .a => .a
    | .b => .b
    | .c => .c

instance : Group K4 where
  mul_assoc := by decide +revert
  one_mul := by decide +revert
  mul_one := by decide +revert
  inv_mul_cancel := by decide +revert
  mul_inv_cancel := by decide +revert

lemma order_dvd_of_npow_eq_one (x : G) (n : ℕ) (h : x ^ n = 1) : order x ∣ n := by
  rw [← zpow_natCast, ← mem_annihilatingIndices_iff,
    annihilatingSubgroup_eq_multiplesOf, zmem_multiplesOf_iff] at h
  exact_mod_cast h

lemma order_K4_a : order K4.a = 2 := by
  have h := order_dvd_of_npow_eq_one K4.a 2 (by decide)
  rw [Nat.dvd_prime Nat.prime_two] at h
  have a_pow_order : (K4.a) ^ order K4.a = 1 := zpow_order_eq_one' K4.a
  obtain h | h := h
  · rw [h] at a_pow_order
    contradiction
  exact h

-- An element x has order n if n is the smallest positive integer such that x^n = 1
-- This is an alternate way to prove that ord(S3.x) = 3, ord(S3.y) = 2

attribute [-instance] S3.instHPowNat
attribute [instance] S3.instHPowInt

lemma order_x : order (S3.x) = 3 := by
  have h := order_dvd_of_npow_eq_one S3.x 3 (by
    ext i
    fin_cases i <;> rfl)
  rw [Nat.dvd_prime Nat.prime_three] at h
  have a_pow_order : (S3.x) ^ order (S3.x) = 1 := by
    apply zpow_order_eq_one'
  obtain h | h := h
  · rw [h] at a_pow_order
    contradiction
  exact h

def IsCyclic (G : Type) [Group G] : Prop := ∃ x : G, IsGenerator x



end Artin
