import Playground.Geometry.SmallGroups.SmallGroups

-- Evaluate CommutingFraction for all groups
#eval Group.CommutingFraction Gap_1_1
#eval Group.CommutingFraction Gap_2_1
#eval Group.CommutingFraction Gap_3_1
#eval Group.CommutingFraction Gap_4_1
#eval Group.CommutingFraction Gap_4_2
#eval Group.CommutingFraction Gap_5_1
#eval Group.CommutingFraction Gap_6_1
#eval Group.CommutingFraction Gap_6_2
#eval Group.CommutingFraction Gap_7_1
#eval Group.CommutingFraction Gap_8_1
#eval Group.CommutingFraction Gap_8_2
#eval Group.CommutingFraction Gap_8_3
#eval Group.CommutingFraction Gap_8_4
#eval Group.CommutingFraction Gap_8_5
#eval Group.CommutingFraction Gap_9_1
#eval Group.CommutingFraction Gap_9_2
#eval Group.CommutingFraction Gap_10_1
#eval Group.CommutingFraction Gap_10_2
#eval Group.CommutingFraction Gap_11_1
#eval Group.CommutingFraction Z12
#eval Group.CommutingFraction Gap_12_2
#eval Group.CommutingFraction Gap_12_3
#eval Group.CommutingFraction Gap_12_4
#eval Group.CommutingFraction Gap_12_5
#eval Group.CommutingFraction Gap_13_1
#eval Group.CommutingFraction Gap_14_1
#eval Group.CommutingFraction Gap_14_2
#eval Group.CommutingFraction Gap_15_1
#eval Group.CommutingFraction Gap_16_1
#eval Group.CommutingFraction Gap_16_2
#eval Group.CommutingFraction Gap_16_5
#eval Group.CommutingFraction Gap_16_7
#eval Group.CommutingFraction Gap_16_9
#eval Group.CommutingFraction Gap_16_10
#eval Group.CommutingFraction Gap_16_11
#eval Group.CommutingFraction Gap_16_12
#eval Group.CommutingFraction Gap_16_14
#eval Group.CommutingFraction Gap_17_1
#eval Group.CommutingFraction Gap_18_1
#eval Group.CommutingFraction Gap_18_2
#eval Group.CommutingFraction Gap_18_3
#eval Group.CommutingFraction Gap_18_5
#eval Group.CommutingFraction Gap_19_1
#eval Group.CommutingFraction Gap_20_2
#eval Group.CommutingFraction Gap_20_4
#eval Group.CommutingFraction Gap_20_5
#eval Group.CommutingFraction Gap_21_2
#eval Group.CommutingFraction Gap_22_1
#eval Group.CommutingFraction Gap_22_2
#eval Group.CommutingFraction Gap_23_1
#eval Group.CommutingFraction Gap_24_2
#eval Group.CommutingFraction Gap_24_5
#eval Group.CommutingFraction Gap_24_6
#eval Group.CommutingFraction Gap_24_9
#eval Group.CommutingFraction Gap_24_10
#eval Group.CommutingFraction Gap_24_11
#eval Group.CommutingFraction Gap_24_12
#eval Group.CommutingFraction Gap_24_13
#eval Group.CommutingFraction Gap_24_14
#eval Group.CommutingFraction Gap_24_15
#eval Group.CommutingFraction Gap_25_1
#eval Group.CommutingFraction Gap_25_2
#eval Group.CommutingFraction Gap_26_1
#eval Group.CommutingFraction Gap_26_2
#eval Group.CommutingFraction Gap_27_1
#eval Group.CommutingFraction Gap_27_2
#eval Group.CommutingFraction Gap_27_5
#eval Group.CommutingFraction Gap_28_2
#eval Group.CommutingFraction Gap_28_3
#eval Group.CommutingFraction Gap_28_4
#eval Group.CommutingFraction Gap_29_1
#eval Group.CommutingFraction Gap_30_1
#eval Group.CommutingFraction Gap_30_2
#eval Group.CommutingFraction Gap_30_3
#eval Group.CommutingFraction Gap_30_4
#eval Group.CommutingFraction Gap_31_1
#eval Group.CommutingFraction Gap_32_1
#eval Group.CommutingFraction Gap_32_3
#eval Group.CommutingFraction C2_C2_C8
#eval Group.CommutingFraction Gap_32_16
#eval Group.CommutingFraction Gap_32_18
#eval Group.CommutingFraction Gap_32_20
#eval Group.CommutingFraction Gap_32_21
#eval Group.CommutingFraction Gap_32_25
#eval Group.CommutingFraction Gap_32_26
#eval Group.CommutingFraction Gap_32_36
#eval Group.CommutingFraction Gap_32_39
#eval Group.CommutingFraction Gap_32_41
#eval Group.CommutingFraction Gap_32_45
#eval Group.CommutingFraction Gap_32_46
#eval Group.CommutingFraction Gap_32_47
#eval Group.CommutingFraction Gap_32_51
#eval Group.CommutingFraction Gap_33_1
#eval Group.CommutingFraction Gap_34_1
#eval Group.CommutingFraction Gap_34_2
#eval Group.CommutingFraction Gap_35_1
#eval Group.CommutingFraction Gap_36_2
#eval Group.CommutingFraction Gap_36_4
#eval Group.CommutingFraction Gap_36_5
#eval Group.CommutingFraction Gap_36_8
#eval Group.CommutingFraction C3_Dih6
#eval Group.CommutingFraction Gap_36_11
#eval Group.CommutingFraction Gap_36_12
#eval Group.CommutingFraction Gap_36_14
#eval Group.CommutingFraction Gap_37_1
#eval Group.CommutingFraction Gap_38_1
#eval Group.CommutingFraction Gap_38_2
#eval Group.CommutingFraction Z39
#eval Group.CommutingFraction Gap_39_2
#eval Group.CommutingFraction Gap_40_2
#eval Group.CommutingFraction Gap_40_5
#eval Group.CommutingFraction Gap_40_6
#eval Group.CommutingFraction C2_C20
#eval Group.CommutingFraction Gap_40_9
#eval Group.CommutingFraction Gap_40_10
#eval Group.CommutingFraction Gap_40_11
#eval Group.CommutingFraction C2_C2_C10
#eval Group.CommutingFraction Gap_40_13
#eval Group.CommutingFraction Gap_40_14
#eval Group.CommutingFraction Gap_41_1
#eval Group.CommutingFraction Gap_42_3
#eval Group.CommutingFraction Gap_42_4
#eval Group.CommutingFraction Gap_42_5
#eval Group.CommutingFraction Gap_42_6
#eval Group.CommutingFraction Gap_43_1
#eval Group.CommutingFraction Gap_44_2
#eval Group.CommutingFraction Gap_44_3
#eval Group.CommutingFraction Gap_44_4
#eval Group.CommutingFraction Gap_45_1
#eval Group.CommutingFraction Gap_45_2
#eval Group.CommutingFraction Gap_46_1
#eval Group.CommutingFraction Gap_46_2
#eval Group.CommutingFraction Gap_47_1
#eval Group.CommutingFraction Gap_48_2
#eval Group.CommutingFraction C4_C12
#eval Group.CommutingFraction Gap_48_4
#eval Group.CommutingFraction C2_C24
#eval Group.CommutingFraction Gap_48_7
#eval Group.CommutingFraction C2_C2_C12
#eval Group.CommutingFraction Gap_48_20
#eval Group.CommutingFraction Gap_48_23
#eval Group.CommutingFraction Gap_48_25
#eval Group.CommutingFraction Gap_48_27
#eval Group.CommutingFraction Gap_48_31
#eval Group.CommutingFraction Gap_48_35
#eval Group.CommutingFraction Gap_48_36
#eval Group.CommutingFraction Gap_48_38
#eval Group.CommutingFraction Gap_48_40
#eval Group.CommutingFraction Gap_48_44
#eval Group.CommutingFraction Gap_48_45
#eval Group.CommutingFraction Gap_48_46
#eval Group.CommutingFraction Gap_48_48
#eval Group.CommutingFraction Gap_48_49
#eval Group.CommutingFraction C2_C2_C2_C6
#eval Group.CommutingFraction Gap_48_51
#eval Group.CommutingFraction Gap_48_52
#eval Group.CommutingFraction Gap_49_1
#eval Group.CommutingFraction Gap_49_2
#eval Group.CommutingFraction Gap_50_1
#eval Group.CommutingFraction Gap_50_2
#eval Group.CommutingFraction Gap_50_3
#eval Group.CommutingFraction Gap_50_5
#eval Group.CommutingFraction Gap_51_1
#eval Group.CommutingFraction Gap_52_2
#eval Group.CommutingFraction Gap_52_4
#eval Group.CommutingFraction Gap_52_5
#eval Group.CommutingFraction Gap_53_1
#eval Group.CommutingFraction Gap_54_1
#eval Group.CommutingFraction Gap_54_2
#eval Group.CommutingFraction Gap_54_3
#eval Group.CommutingFraction Gap_54_4
#eval Group.CommutingFraction C3_Dih9
#eval Group.CommutingFraction Gap_54_9
#eval Group.CommutingFraction Gap_54_12
#eval Group.CommutingFraction Gap_54_15
#eval Group.CommutingFraction Gap_55_1
#eval Group.CommutingFraction Z55
#eval Group.CommutingFraction Gap_56_2
#eval Group.CommutingFraction Gap_56_4
#eval Group.CommutingFraction Gap_56_5
#eval Group.CommutingFraction Gap_56_8
#eval Group.CommutingFraction Gap_56_9
#eval Group.CommutingFraction Gap_56_10
#eval Group.CommutingFraction C2_C2_C14
#eval Group.CommutingFraction Gap_56_12
#eval Group.CommutingFraction Gap_56_13
#eval Group.CommutingFraction Gap_57_2
#eval Group.CommutingFraction Gap_58_1
#eval Group.CommutingFraction Gap_58_2
#eval Group.CommutingFraction Gap_59_1
#eval Group.CommutingFraction Gap_60_4
#eval Group.CommutingFraction Gap_60_5
#eval Group.CommutingFraction C2_C30
#eval Group.CommutingFraction Gap_60_8
#eval Group.CommutingFraction Gap_60_9
#eval Group.CommutingFraction Gap_60_10
#eval Group.CommutingFraction Gap_60_11
#eval Group.CommutingFraction Gap_60_12
#eval Group.CommutingFraction Gap_60_13
