import Playground.Geometry.SmallGroups.SmallGroups

-- Evaluate FracInvolutions for all groups
#eval Group.FracInvolutions Trivial
#eval Group.FracInvolutions Z2
#eval Group.FracInvolutions Z3
#eval Group.FracInvolutions Z4
#eval Group.FracInvolutions V4
#eval Group.FracInvolutions Z5
#eval Group.FracInvolutions Z6
#eval Group.FracInvolutions S3
#eval Group.FracInvolutions Z7
#eval Group.FracInvolutions Z8
#eval Group.FracInvolutions C4_C2
#eval Group.FracInvolutions Dih4
#eval Group.FracInvolutions Q
#eval Group.FracInvolutions E8
#eval Group.FracInvolutions Z9
#eval Group.FracInvolutions E9
#eval Group.FracInvolutions Dih5
#eval Group.FracInvolutions Z10
#eval Group.FracInvolutions Z11
#eval Group.FracInvolutions Z12
#eval Group.FracInvolutions A4
#eval Group.FracInvolutions Dih6
#eval Group.FracInvolutions C2_C6
#eval Group.FracInvolutions Z13
#eval Group.FracInvolutions Dih7
#eval Group.FracInvolutions Z14
#eval Group.FracInvolutions Z15
#eval Group.FracInvolutions Z16
#eval Group.FracInvolutions C4_C4
#eval Group.FracInvolutions C2_C8
#eval Group.FracInvolutions Dih8
#eval Group.FracInvolutions C2_C2_C4
#eval Group.FracInvolutions C2_Dih4
#eval Group.FracInvolutions C2_Q
#eval Group.FracInvolutions C2_C2_C2_C2
#eval Group.FracInvolutions Z17
#eval Group.FracInvolutions Dih9
#eval Group.FracInvolutions Z18
#eval Group.FracInvolutions C3_S3
#eval Group.FracInvolutions C3_C6
#eval Group.FracInvolutions Z19
#eval Group.FracInvolutions Z20
#eval Group.FracInvolutions Dih10
#eval Group.FracInvolutions C2_C10
#eval Group.FracInvolutions Z21
#eval Group.FracInvolutions Dih11
#eval Group.FracInvolutions Z22
#eval Group.FracInvolutions Z23
#eval Group.FracInvolutions Z24
#eval Group.FracInvolutions C4_S3
#eval Group.FracInvolutions Dih12
#eval Group.FracInvolutions C2_C12
#eval Group.FracInvolutions C3_Dih4
#eval Group.FracInvolutions C3_Q
#eval Group.FracInvolutions S4
#eval Group.FracInvolutions C2_A4
#eval Group.FracInvolutions C2_C2_S3
#eval Group.FracInvolutions C2_C2_C6
#eval Group.FracInvolutions Z25
#eval Group.FracInvolutions C5_C5
#eval Group.FracInvolutions Dih13
#eval Group.FracInvolutions Z26
#eval Group.FracInvolutions Z27
#eval Group.FracInvolutions C3_C9
#eval Group.FracInvolutions C3_C3_C3
#eval Group.FracInvolutions Z28
#eval Group.FracInvolutions Dih14
#eval Group.FracInvolutions C2_C14
#eval Group.FracInvolutions Z29
#eval Group.FracInvolutions S3_C5
#eval Group.FracInvolutions C5_S3
#eval Group.FracInvolutions Dih15
#eval Group.FracInvolutions Z30
#eval Group.FracInvolutions Z31
#eval Group.FracInvolutions Z32
#eval Group.FracInvolutions C4_C8
#eval Group.FracInvolutions C2_C2_C8
#eval Group.FracInvolutions C2_C16
#eval Group.FracInvolutions Dih16
#eval Group.FracInvolutions C2_C4_C4
#eval Group.FracInvolutions C2_C2_C2_C4
#eval Group.FracInvolutions C2_Dih8
#eval Group.FracInvolutions Z33
#eval Group.FracInvolutions Dih17
#eval Group.FracInvolutions Z34
#eval Group.FracInvolutions Z35
#eval Group.FracInvolutions Z36
#eval Group.FracInvolutions Dih18
#eval Group.FracInvolutions C2_C18
#eval Group.FracInvolutions C3_C12
#eval Group.FracInvolutions C3_Dih6
#eval Group.FracInvolutions C6_C6
#eval Group.FracInvolutions Z37
#eval Group.FracInvolutions Dih19
#eval Group.FracInvolutions Z38
#eval Group.FracInvolutions Z39
#eval Group.FracInvolutions Z40
#eval Group.FracInvolutions C4_Dih5
#eval Group.FracInvolutions Dih20
#eval Group.FracInvolutions C2_C20
#eval Group.FracInvolutions C5_Dih4
#eval Group.FracInvolutions C2_C2_C10
#eval Group.FracInvolutions Z41
#eval Group.FracInvolutions C7_S3
#eval Group.FracInvolutions Dih21
#eval Group.FracInvolutions Z42
#eval Group.FracInvolutions Z43
#eval Group.FracInvolutions Z44
#eval Group.FracInvolutions Dih22
#eval Group.FracInvolutions Z45
#eval Group.FracInvolutions C3_C15
#eval Group.FracInvolutions Dih23
#eval Group.FracInvolutions Z46
#eval Group.FracInvolutions Z47
#eval Group.FracInvolutions Z48
#eval Group.FracInvolutions Dih24
#eval Group.FracInvolutions C4_C12
#eval Group.FracInvolutions C2_C24
#eval Group.FracInvolutions C4_A4
#eval Group.FracInvolutions C2_C2_C12
#eval Group.FracInvolutions C2_S4
#eval Group.FracInvolutions C2_C2_C2_C6
#eval Group.FracInvolutions Z49
#eval Group.FracInvolutions Dih25
#eval Group.FracInvolutions Z50
#eval Group.FracInvolutions C5_Dih5
#eval Group.FracInvolutions C5_C10
#eval Group.FracInvolutions Z51
#eval Group.FracInvolutions Z52
#eval Group.FracInvolutions Dih26
#eval Group.FracInvolutions Z53
#eval Group.FracInvolutions Dih27
#eval Group.FracInvolutions Z54
#eval Group.FracInvolutions C3_Dih9
#eval Group.FracInvolutions C3_C18
#eval Group.FracInvolutions C3_C3_C6
#eval Group.FracInvolutions Z55
#eval Group.FracInvolutions Z56
#eval Group.FracInvolutions Dih28
#eval Group.FracInvolutions C2_C28
#eval Group.FracInvolutions C2_C2_C14
#eval Group.FracInvolutions Z57
#eval Group.FracInvolutions Dih29
#eval Group.FracInvolutions Z58
#eval Group.FracInvolutions Z59
#eval Group.FracInvolutions Z60
#eval Group.FracInvolutions A5
#eval Group.FracInvolutions C5_A4
#eval Group.FracInvolutions Dih30
#eval Group.FracInvolutions C2_C30
