import Playground.Geometry.SmallGroups.SmallGroups

-- Evaluate CommutingFraction for all groups
#eval Group.CommutingFraction Trivial
#eval Group.CommutingFraction Z2
#eval Group.CommutingFraction Z3
#eval Group.CommutingFraction Z4
#eval Group.CommutingFraction V4
#eval Group.CommutingFraction Z5
#eval Group.CommutingFraction Z6
#eval Group.CommutingFraction S3
#eval Group.CommutingFraction Z7
#eval Group.CommutingFraction Z8
#eval Group.CommutingFraction C4_C2
#eval Group.CommutingFraction Dih4
#eval Group.CommutingFraction Q
#eval Group.CommutingFraction E8
#eval Group.CommutingFraction Z9
#eval Group.CommutingFraction E9
#eval Group.CommutingFraction Dih5
#eval Group.CommutingFraction Z10
#eval Group.CommutingFraction Z11
#eval Group.CommutingFraction Z12
#eval Group.CommutingFraction A4
#eval Group.CommutingFraction Dih6
#eval Group.CommutingFraction C2_C6
#eval Group.CommutingFraction Z13
#eval Group.CommutingFraction Dih7
#eval Group.CommutingFraction Z14
#eval Group.CommutingFraction Z15
#eval Group.CommutingFraction Z16
#eval Group.CommutingFraction C4_C4
#eval Group.CommutingFraction C2_C8
#eval Group.CommutingFraction Dih8
#eval Group.CommutingFraction C2_C2_C4
#eval Group.CommutingFraction C2_Dih4
#eval Group.CommutingFraction C2_Q
#eval Group.CommutingFraction C2_C2_C2_C2
#eval Group.CommutingFraction Z17
#eval Group.CommutingFraction Dih9
#eval Group.CommutingFraction Z18
#eval Group.CommutingFraction C3_S3
#eval Group.CommutingFraction C3_C6
#eval Group.CommutingFraction Z19
#eval Group.CommutingFraction Z20
#eval Group.CommutingFraction Dih10
#eval Group.CommutingFraction C2_C10
#eval Group.CommutingFraction Z21
#eval Group.CommutingFraction Dih11
#eval Group.CommutingFraction Z22
#eval Group.CommutingFraction Z23
#eval Group.CommutingFraction Z24
#eval Group.CommutingFraction C4_S3
#eval Group.CommutingFraction Dih12
#eval Group.CommutingFraction C2_C12
#eval Group.CommutingFraction C3_Dih4
#eval Group.CommutingFraction C3_Q
#eval Group.CommutingFraction S4
#eval Group.CommutingFraction C2_A4
#eval Group.CommutingFraction C2_C2_S3
#eval Group.CommutingFraction C2_C2_C6
#eval Group.CommutingFraction Z25
#eval Group.CommutingFraction C5_C5
#eval Group.CommutingFraction Dih13
#eval Group.CommutingFraction Z26
#eval Group.CommutingFraction Z27
#eval Group.CommutingFraction C3_C9
#eval Group.CommutingFraction C3_C3_C3
#eval Group.CommutingFraction Z28
#eval Group.CommutingFraction Dih14
#eval Group.CommutingFraction C2_C14
#eval Group.CommutingFraction Z29
#eval Group.CommutingFraction S3_C5
#eval Group.CommutingFraction C5_S3
#eval Group.CommutingFraction Dih15
#eval Group.CommutingFraction Z30
#eval Group.CommutingFraction Z31
#eval Group.CommutingFraction Z32
#eval Group.CommutingFraction C4_C8
#eval Group.CommutingFraction C2_C2_C8
#eval Group.CommutingFraction C2_C16
#eval Group.CommutingFraction Dih16
#eval Group.CommutingFraction C2_C4_C4
#eval Group.CommutingFraction C2_C2_C2_C4
#eval Group.CommutingFraction C2_Dih8
#eval Group.CommutingFraction Z33
#eval Group.CommutingFraction Dih17
#eval Group.CommutingFraction Z34
#eval Group.CommutingFraction Z35
#eval Group.CommutingFraction Z36
#eval Group.CommutingFraction Dih18
#eval Group.CommutingFraction C2_C18
#eval Group.CommutingFraction C3_C12
#eval Group.CommutingFraction C3_Dih6
#eval Group.CommutingFraction C6_C6
#eval Group.CommutingFraction Z37
#eval Group.CommutingFraction Dih19
#eval Group.CommutingFraction Z38
#eval Group.CommutingFraction Z39
#eval Group.CommutingFraction Z40
#eval Group.CommutingFraction C4_Dih5
#eval Group.CommutingFraction Dih20
#eval Group.CommutingFraction C2_C20
#eval Group.CommutingFraction C5_Dih4
#eval Group.CommutingFraction C2_C2_C10
#eval Group.CommutingFraction Z41
#eval Group.CommutingFraction C7_S3
#eval Group.CommutingFraction Dih21
#eval Group.CommutingFraction Z42
#eval Group.CommutingFraction Z43
#eval Group.CommutingFraction Z44
#eval Group.CommutingFraction Dih22
#eval Group.CommutingFraction Z45
#eval Group.CommutingFraction C3_C15
#eval Group.CommutingFraction Dih23
#eval Group.CommutingFraction Z46
#eval Group.CommutingFraction Z47
#eval Group.CommutingFraction Z48
#eval Group.CommutingFraction Dih24
#eval Group.CommutingFraction C4_C12
#eval Group.CommutingFraction C2_C24
#eval Group.CommutingFraction C4_A4
#eval Group.CommutingFraction C2_C2_C12
#eval Group.CommutingFraction C2_S4
#eval Group.CommutingFraction C2_C2_C2_C6
#eval Group.CommutingFraction Z49
#eval Group.CommutingFraction Dih25
#eval Group.CommutingFraction Z50
#eval Group.CommutingFraction C5_Dih5
#eval Group.CommutingFraction C5_C10
#eval Group.CommutingFraction Z51
#eval Group.CommutingFraction Z52
#eval Group.CommutingFraction Dih26
#eval Group.CommutingFraction Z53
#eval Group.CommutingFraction Dih27
#eval Group.CommutingFraction Z54
#eval Group.CommutingFraction C3_Dih9
#eval Group.CommutingFraction C3_C18
#eval Group.CommutingFraction C3_C3_C6
#eval Group.CommutingFraction Z55
#eval Group.CommutingFraction Z56
#eval Group.CommutingFraction Dih28
#eval Group.CommutingFraction C2_C28
#eval Group.CommutingFraction C2_C2_C14
#eval Group.CommutingFraction Z57
#eval Group.CommutingFraction Dih29
#eval Group.CommutingFraction Z58
#eval Group.CommutingFraction Z59
#eval Group.CommutingFraction Z60
#eval Group.CommutingFraction A5
#eval Group.CommutingFraction C5_A4
#eval Group.CommutingFraction Dih30
#eval Group.CommutingFraction C2_C30
