import Playground.Geometry.SmallGroups.SmallGroups

-- Evaluate IsAbelian for all groups
#eval Group.IsAbelian Trivial
#eval Group.IsAbelian Z2
#eval Group.IsAbelian Z3
#eval Group.IsAbelian Z4
#eval Group.IsAbelian V4
#eval Group.IsAbelian Z5
#eval Group.IsAbelian Z6
#eval Group.IsAbelian S3
#eval Group.IsAbelian Z7
#eval Group.IsAbelian Z8
#eval Group.IsAbelian C4_C2
#eval Group.IsAbelian Dih4
#eval Group.IsAbelian Q
#eval Group.IsAbelian E8
#eval Group.IsAbelian Z9
#eval Group.IsAbelian E9
#eval Group.IsAbelian Dih5
#eval Group.IsAbelian Z10
#eval Group.IsAbelian Z11
#eval Group.IsAbelian Z12
#eval Group.IsAbelian A4
#eval Group.IsAbelian Dih6
#eval Group.IsAbelian C2_C6
#eval Group.IsAbelian Z13
#eval Group.IsAbelian Dih7
#eval Group.IsAbelian Z14
#eval Group.IsAbelian Z15
#eval Group.IsAbelian Z16
#eval Group.IsAbelian C4_C4
#eval Group.IsAbelian C2_C8
#eval Group.IsAbelian Dih8
#eval Group.IsAbelian C2_C2_C4
#eval Group.IsAbelian C2_Dih4
#eval Group.IsAbelian C2_Q
#eval Group.IsAbelian C2_C2_C2_C2
#eval Group.IsAbelian Z17
#eval Group.IsAbelian Dih9
#eval Group.IsAbelian Z18
#eval Group.IsAbelian C3_S3
#eval Group.IsAbelian C3_C6
#eval Group.IsAbelian Z19
#eval Group.IsAbelian Z20
#eval Group.IsAbelian Dih10
#eval Group.IsAbelian C2_C10
#eval Group.IsAbelian Z21
#eval Group.IsAbelian Dih11
#eval Group.IsAbelian Z22
#eval Group.IsAbelian Z23
#eval Group.IsAbelian Z24
#eval Group.IsAbelian C4_S3
#eval Group.IsAbelian Dih12
#eval Group.IsAbelian C2_C12
#eval Group.IsAbelian C3_Dih4
#eval Group.IsAbelian C3_Q
#eval Group.IsAbelian S4
#eval Group.IsAbelian C2_A4
#eval Group.IsAbelian C2_C2_S3
#eval Group.IsAbelian C2_C2_C6
#eval Group.IsAbelian Z25
#eval Group.IsAbelian C5_C5
#eval Group.IsAbelian Dih13
#eval Group.IsAbelian Z26
#eval Group.IsAbelian Z27
#eval Group.IsAbelian C3_C9
#eval Group.IsAbelian C3_C3_C3
#eval Group.IsAbelian Z28
#eval Group.IsAbelian Dih14
#eval Group.IsAbelian C2_C14
#eval Group.IsAbelian Z29
#eval Group.IsAbelian S3_C5
#eval Group.IsAbelian C5_S3
#eval Group.IsAbelian Dih15
#eval Group.IsAbelian Z30
#eval Group.IsAbelian Z31
#eval Group.IsAbelian Z32
#eval Group.IsAbelian C4_C8
#eval Group.IsAbelian C2_C2_C8
#eval Group.IsAbelian C2_C16
#eval Group.IsAbelian Dih16
#eval Group.IsAbelian C2_C4_C4
#eval Group.IsAbelian C2_C2_C2_C4
#eval Group.IsAbelian C2_Dih8
#eval Group.IsAbelian Z33
#eval Group.IsAbelian Dih17
#eval Group.IsAbelian Z34
#eval Group.IsAbelian Z35
#eval Group.IsAbelian Z36
#eval Group.IsAbelian Dih18
#eval Group.IsAbelian C2_C18
#eval Group.IsAbelian C3_C12
#eval Group.IsAbelian C3_Dih6
#eval Group.IsAbelian C6_C6
#eval Group.IsAbelian Z37
#eval Group.IsAbelian Dih19
#eval Group.IsAbelian Z38
#eval Group.IsAbelian Z39
#eval Group.IsAbelian Z40
#eval Group.IsAbelian C4_Dih5
#eval Group.IsAbelian Dih20
#eval Group.IsAbelian C2_C20
#eval Group.IsAbelian C5_Dih4
#eval Group.IsAbelian C2_C2_C10
#eval Group.IsAbelian Z41
#eval Group.IsAbelian C7_S3
#eval Group.IsAbelian Dih21
#eval Group.IsAbelian Z42
#eval Group.IsAbelian Z43
#eval Group.IsAbelian Z44
#eval Group.IsAbelian Dih22
#eval Group.IsAbelian Z45
#eval Group.IsAbelian C3_C15
#eval Group.IsAbelian Dih23
#eval Group.IsAbelian Z46
#eval Group.IsAbelian Z47
#eval Group.IsAbelian Z48
#eval Group.IsAbelian Dih24
#eval Group.IsAbelian C4_C12
#eval Group.IsAbelian C2_C24
#eval Group.IsAbelian C4_A4
#eval Group.IsAbelian C2_C2_C12
#eval Group.IsAbelian C2_S4
#eval Group.IsAbelian C2_C2_C2_C6
#eval Group.IsAbelian Z49
#eval Group.IsAbelian Dih25
#eval Group.IsAbelian Z50
#eval Group.IsAbelian C5_Dih5
#eval Group.IsAbelian C5_C10
#eval Group.IsAbelian Z51
#eval Group.IsAbelian Z52
#eval Group.IsAbelian Dih26
#eval Group.IsAbelian Z53
#eval Group.IsAbelian Dih27
#eval Group.IsAbelian Z54
#eval Group.IsAbelian C3_Dih9
#eval Group.IsAbelian C3_C18
#eval Group.IsAbelian C3_C3_C6
#eval Group.IsAbelian Z55
#eval Group.IsAbelian Z56
#eval Group.IsAbelian Dih28
#eval Group.IsAbelian C2_C28
#eval Group.IsAbelian C2_C2_C14
#eval Group.IsAbelian Z57
#eval Group.IsAbelian Dih29
#eval Group.IsAbelian Z58
#eval Group.IsAbelian Z59
#eval Group.IsAbelian Z60
#eval Group.IsAbelian A5
#eval Group.IsAbelian C5_A4
#eval Group.IsAbelian Dih30
#eval Group.IsAbelian C2_C30
