import Playground.Geometry.SmallGroups.SmallGroups

-- Evaluate Cardinality for all groups
#eval Fintype.card Trivial
#eval Fintype.card Z2
#eval Fintype.card Z3
#eval Fintype.card Z4
#eval Fintype.card V4
#eval Fintype.card Z5
#eval Fintype.card Z6
#eval Fintype.card S3
#eval Fintype.card Z7
#eval Fintype.card Z8
#eval Fintype.card C4_C2
#eval Fintype.card Dih4
#eval Fintype.card Q
#eval Fintype.card E8
#eval Fintype.card Z9
#eval Fintype.card E9
#eval Fintype.card Dih5
#eval Fintype.card Z10
#eval Fintype.card Z11
#eval Fintype.card Z12
#eval Fintype.card A4
#eval Fintype.card Dih6
#eval Fintype.card C2_C6
#eval Fintype.card Z13
#eval Fintype.card Dih7
#eval Fintype.card Z14
#eval Fintype.card Z15
#eval Fintype.card Z16
#eval Fintype.card C4_C4
#eval Fintype.card C2_C8
#eval Fintype.card Dih8
#eval Fintype.card C2_C2_C4
#eval Fintype.card C2_Dih4
#eval Fintype.card C2_Q
#eval Fintype.card C2_C2_C2_C2
#eval Fintype.card Z17
#eval Fintype.card Dih9
#eval Fintype.card Z18
#eval Fintype.card C3_S3
#eval Fintype.card C3_C6
#eval Fintype.card Z19
#eval Fintype.card Z20
#eval Fintype.card Dih10
#eval Fintype.card C2_C10
#eval Fintype.card Z21
#eval Fintype.card Dih11
#eval Fintype.card Z22
#eval Fintype.card Z23
#eval Fintype.card Z24
#eval Fintype.card C4_S3
#eval Fintype.card Dih12
#eval Fintype.card C2_C12
#eval Fintype.card C3_Dih4
#eval Fintype.card C3_Q
#eval Fintype.card S4
#eval Fintype.card C2_A4
#eval Fintype.card C2_C2_S3
#eval Fintype.card C2_C2_C6
#eval Fintype.card Z25
#eval Fintype.card C5_C5
#eval Fintype.card Dih13
#eval Fintype.card Z26
#eval Fintype.card Z27
#eval Fintype.card C3_C9
#eval Fintype.card C3_C3_C3
#eval Fintype.card Z28
#eval Fintype.card Dih14
#eval Fintype.card C2_C14
#eval Fintype.card Z29
#eval Fintype.card S3_C5
#eval Fintype.card C5_S3
#eval Fintype.card Dih15
#eval Fintype.card Z30
#eval Fintype.card Z31
#eval Fintype.card Z32
#eval Fintype.card C4_C8
#eval Fintype.card C2_C2_C8
#eval Fintype.card C2_C16
#eval Fintype.card Dih16
#eval Fintype.card C2_C4_C4
#eval Fintype.card C2_C2_C2_C4
#eval Fintype.card C2_Dih8
#eval Fintype.card Z33
#eval Fintype.card Dih17
#eval Fintype.card Z34
#eval Fintype.card Z35
#eval Fintype.card Z36
#eval Fintype.card Dih18
#eval Fintype.card C2_C18
#eval Fintype.card C3_C12
#eval Fintype.card C3_Dih6
#eval Fintype.card C6_C6
#eval Fintype.card Z37
#eval Fintype.card Dih19
#eval Fintype.card Z38
#eval Fintype.card Z39
#eval Fintype.card Z40
#eval Fintype.card C4_Dih5
#eval Fintype.card Dih20
#eval Fintype.card C2_C20
#eval Fintype.card C5_Dih4
#eval Fintype.card C2_C2_C10
#eval Fintype.card Z41
#eval Fintype.card C7_S3
#eval Fintype.card Dih21
#eval Fintype.card Z42
#eval Fintype.card Z43
#eval Fintype.card Z44
#eval Fintype.card Dih22
#eval Fintype.card Z45
#eval Fintype.card C3_C15
#eval Fintype.card Dih23
#eval Fintype.card Z46
#eval Fintype.card Z47
#eval Fintype.card Z48
#eval Fintype.card Dih24
#eval Fintype.card C4_C12
#eval Fintype.card C2_C24
#eval Fintype.card C4_A4
#eval Fintype.card C2_C2_C12
#eval Fintype.card C2_S4
#eval Fintype.card C2_C2_C2_C6
#eval Fintype.card Z49
#eval Fintype.card Dih25
#eval Fintype.card Z50
#eval Fintype.card C5_Dih5
#eval Fintype.card C5_C10
#eval Fintype.card Z51
#eval Fintype.card Z52
#eval Fintype.card Dih26
#eval Fintype.card Z53
#eval Fintype.card Dih27
#eval Fintype.card Z54
#eval Fintype.card C3_Dih9
#eval Fintype.card C3_C18
#eval Fintype.card C3_C3_C6
#eval Fintype.card Z55
#eval Fintype.card Z56
#eval Fintype.card Dih28
#eval Fintype.card C2_C28
#eval Fintype.card C2_C2_C14
#eval Fintype.card Z57
#eval Fintype.card Dih29
#eval Fintype.card Z58
#eval Fintype.card Z59
#eval Fintype.card Z60
#eval Fintype.card A5
#eval Fintype.card C5_A4
#eval Fintype.card Dih30
#eval Fintype.card C2_C30
