import Playground.Geometry.SmallGroups.SmallGroups

-- Evaluate NumSubgroups for all groups
#eval Group.numSubgroups Trivial
#eval Group.numSubgroups Z2
#eval Group.numSubgroups Z3
#eval Group.numSubgroups Z4
#eval Group.numSubgroups V4
#eval Group.numSubgroups Z5
#eval Group.numSubgroups Z6
#eval Group.numSubgroups S3
#eval Group.numSubgroups Z7
#eval Group.numSubgroups Z8
#eval Group.numSubgroups C4_C2
#eval Group.numSubgroups Dih4
#eval Group.numSubgroups Q
#eval Group.numSubgroups E8
#eval Group.numSubgroups Z9
#eval Group.numSubgroups E9
#eval Group.numSubgroups Dih5
#eval Group.numSubgroups Z10
#eval Group.numSubgroups Z11
#eval Group.numSubgroups Z12
#eval Group.numSubgroups A4
#eval Group.numSubgroups Dih6
#eval Group.numSubgroups C2_C6
#eval Group.numSubgroups Z13
#eval Group.numSubgroups Dih7
#eval Group.numSubgroups Z14
#eval Group.numSubgroups Z15
#eval Group.numSubgroups Z16
#eval Group.numSubgroups C4_C4
#eval Group.numSubgroups C2_C8
#eval Group.numSubgroups Dih8
#eval Group.numSubgroups C2_C2_C4
#eval Group.numSubgroups C2_Dih4
#eval Group.numSubgroups C2_Q
#eval Group.numSubgroups C2_C2_C2_C2
#eval Group.numSubgroups Z17
#eval Group.numSubgroups Dih9
#eval Group.numSubgroups Z18
#eval Group.numSubgroups C3_S3
#eval Group.numSubgroups C3_C6
#eval Group.numSubgroups Z19
#eval Group.numSubgroups Z20
#eval Group.numSubgroups Dih10
#eval Group.numSubgroups C2_C10
#eval Group.numSubgroups Z21
#eval Group.numSubgroups Dih11
#eval Group.numSubgroups Z22
#eval Group.numSubgroups Z23
#eval Group.numSubgroups Z24
#eval Group.numSubgroups C4_S3
#eval Group.numSubgroups Dih12
#eval Group.numSubgroups C2_C12
#eval Group.numSubgroups C3_Dih4
#eval Group.numSubgroups C3_Q
#eval Group.numSubgroups S4
#eval Group.numSubgroups C2_A4
#eval Group.numSubgroups C2_C2_S3
#eval Group.numSubgroups C2_C2_C6
#eval Group.numSubgroups Z25
#eval Group.numSubgroups C5_C5
#eval Group.numSubgroups Dih13
#eval Group.numSubgroups Z26
#eval Group.numSubgroups Z27
#eval Group.numSubgroups C3_C9
#eval Group.numSubgroups C3_C3_C3
#eval Group.numSubgroups Z28
#eval Group.numSubgroups Dih14
#eval Group.numSubgroups C2_C14
#eval Group.numSubgroups Z29
#eval Group.numSubgroups S3_C5
#eval Group.numSubgroups C5_S3
#eval Group.numSubgroups Dih15
#eval Group.numSubgroups Z30
#eval Group.numSubgroups Z31
#eval Group.numSubgroups Z32
#eval Group.numSubgroups C4_C8
#eval Group.numSubgroups C2_C2_C8
#eval Group.numSubgroups C2_C16
#eval Group.numSubgroups Dih16
#eval Group.numSubgroups C2_C4_C4
#eval Group.numSubgroups C2_C2_C2_C4
#eval Group.numSubgroups C2_Dih8
#eval Group.numSubgroups Z33
#eval Group.numSubgroups Dih17
#eval Group.numSubgroups Z34
#eval Group.numSubgroups Z35
#eval Group.numSubgroups Z36
#eval Group.numSubgroups Dih18
#eval Group.numSubgroups C2_C18
#eval Group.numSubgroups C3_C12
#eval Group.numSubgroups C3_Dih6
#eval Group.numSubgroups C6_C6
#eval Group.numSubgroups Z37
#eval Group.numSubgroups Dih19
#eval Group.numSubgroups Z38
#eval Group.numSubgroups Z39
#eval Group.numSubgroups Z40
#eval Group.numSubgroups C4_Dih5
#eval Group.numSubgroups Dih20
#eval Group.numSubgroups C2_C20
#eval Group.numSubgroups C5_Dih4
#eval Group.numSubgroups C2_C2_C10
#eval Group.numSubgroups Z41
#eval Group.numSubgroups C7_S3
#eval Group.numSubgroups Dih21
#eval Group.numSubgroups Z42
#eval Group.numSubgroups Z43
#eval Group.numSubgroups Z44
#eval Group.numSubgroups Dih22
#eval Group.numSubgroups Z45
#eval Group.numSubgroups C3_C15
#eval Group.numSubgroups Dih23
#eval Group.numSubgroups Z46
#eval Group.numSubgroups Z47
#eval Group.numSubgroups Z48
#eval Group.numSubgroups Dih24
#eval Group.numSubgroups C4_C12
#eval Group.numSubgroups C2_C24
#eval Group.numSubgroups C4_A4
#eval Group.numSubgroups C2_C2_C12
#eval Group.numSubgroups C2_S4
#eval Group.numSubgroups C2_C2_C2_C6
#eval Group.numSubgroups Z49
#eval Group.numSubgroups Dih25
#eval Group.numSubgroups Z50
#eval Group.numSubgroups C5_Dih5
#eval Group.numSubgroups C5_C10
#eval Group.numSubgroups Z51
#eval Group.numSubgroups Z52
#eval Group.numSubgroups Dih26
#eval Group.numSubgroups Z53
#eval Group.numSubgroups Dih27
#eval Group.numSubgroups Z54
#eval Group.numSubgroups C3_Dih9
#eval Group.numSubgroups C3_C18
#eval Group.numSubgroups C3_C3_C6
#eval Group.numSubgroups Z55
#eval Group.numSubgroups Z56
#eval Group.numSubgroups Dih28
#eval Group.numSubgroups C2_C28
#eval Group.numSubgroups C2_C2_C14
#eval Group.numSubgroups Z57
#eval Group.numSubgroups Dih29
#eval Group.numSubgroups Z58
#eval Group.numSubgroups Z59
#eval Group.numSubgroups Z60
#eval Group.numSubgroups A5
#eval Group.numSubgroups C5_A4
#eval Group.numSubgroups Dih30
#eval Group.numSubgroups C2_C30
