import Playground.Geometry.SmallGroups.Gap_1.Gap_1_1
import Playground.Geometry.SmallGroups.Gap_10.Gap_10_1
import Playground.Geometry.SmallGroups.Gap_10.Gap_10_2
import Playground.Geometry.SmallGroups.Gap_11.Gap_11_1
-- import Playground.Geometry.SmallGroups.Gap_12.Gap_12_1  -- DicyclicGroup not available in Mathlib
import Playground.Geometry.SmallGroups.Gap_12.Gap_12_2
import Playground.Geometry.SmallGroups.Gap_12.Gap_12_3
import Playground.Geometry.SmallGroups.Gap_12.Gap_12_4
import Playground.Geometry.SmallGroups.Gap_12.Gap_12_5
import Playground.Geometry.SmallGroups.Gap_13.Gap_13_1
import Playground.Geometry.SmallGroups.Gap_14.Gap_14_1
import Playground.Geometry.SmallGroups.Gap_14.Gap_14_2
import Playground.Geometry.SmallGroups.Gap_15.Gap_15_1
import Playground.Geometry.SmallGroups.Gap_16.Gap_16_1
import Playground.Geometry.SmallGroups.Gap_16.Gap_16_10
import Playground.Geometry.SmallGroups.Gap_16.Gap_16_14
import Playground.Geometry.SmallGroups.Gap_16.Gap_16_2
import Playground.Geometry.SmallGroups.Gap_16.Gap_16_5
import Playground.Geometry.SmallGroups.Gap_16.Gap_16_7
import Playground.Geometry.SmallGroups.Gap_17.Gap_17_1
import Playground.Geometry.SmallGroups.Gap_18.Gap_18_1
import Playground.Geometry.SmallGroups.Gap_18.Gap_18_2
import Playground.Geometry.SmallGroups.Gap_18.Gap_18_5
import Playground.Geometry.SmallGroups.Gap_19.Gap_19_1
import Playground.Geometry.SmallGroups.Gap_2.Gap_2_1
import Playground.Geometry.SmallGroups.Gap_20.Gap_20_2
import Playground.Geometry.SmallGroups.Gap_20.Gap_20_4
import Playground.Geometry.SmallGroups.Gap_20.Gap_20_5
import Playground.Geometry.SmallGroups.Gap_21.Gap_21_2
import Playground.Geometry.SmallGroups.Gap_22.Gap_22_1
import Playground.Geometry.SmallGroups.Gap_22.Gap_22_2
import Playground.Geometry.SmallGroups.Gap_23.Gap_23_1
import Playground.Geometry.SmallGroups.Gap_24.Gap_24_12
import Playground.Geometry.SmallGroups.Gap_24.Gap_24_15
import Playground.Geometry.SmallGroups.Gap_24.Gap_24_2
import Playground.Geometry.SmallGroups.Gap_24.Gap_24_6
import Playground.Geometry.SmallGroups.Gap_24.Gap_24_9
import Playground.Geometry.SmallGroups.Gap_25.Gap_25_1
import Playground.Geometry.SmallGroups.Gap_25.Gap_25_2
import Playground.Geometry.SmallGroups.Gap_26.Gap_26_1
import Playground.Geometry.SmallGroups.Gap_26.Gap_26_2
import Playground.Geometry.SmallGroups.Gap_27.Gap_27_1
import Playground.Geometry.SmallGroups.Gap_27.Gap_27_2
import Playground.Geometry.SmallGroups.Gap_27.Gap_27_5
import Playground.Geometry.SmallGroups.Gap_28.Gap_28_2
import Playground.Geometry.SmallGroups.Gap_28.Gap_28_3
import Playground.Geometry.SmallGroups.Gap_28.Gap_28_4
import Playground.Geometry.SmallGroups.Gap_29.Gap_29_1
import Playground.Geometry.SmallGroups.Gap_3.Gap_3_1
import Playground.Geometry.SmallGroups.Gap_30.Gap_30_3
import Playground.Geometry.SmallGroups.Gap_30.Gap_30_4
import Playground.Geometry.SmallGroups.Gap_31.Gap_31_1
import Playground.Geometry.SmallGroups.Gap_32.Gap_32_1
import Playground.Geometry.SmallGroups.Gap_32.Gap_32_16
import Playground.Geometry.SmallGroups.Gap_32.Gap_32_18
import Playground.Geometry.SmallGroups.Gap_32.Gap_32_21
import Playground.Geometry.SmallGroups.Gap_32.Gap_32_3
import Playground.Geometry.SmallGroups.Gap_32.Gap_32_36
-- import Playground.Geometry.SmallGroups.Gap_32.Gap_32_45  -- 5-way product exceeds instance synthesis depth
import Playground.Geometry.SmallGroups.Gap_32.Gap_32_5
-- import Playground.Geometry.SmallGroups.Gap_32.Gap_32_51  -- 5-way product exceeds instance synthesis depth
import Playground.Geometry.SmallGroups.Gap_33.Gap_33_1
import Playground.Geometry.SmallGroups.Gap_34.Gap_34_1
import Playground.Geometry.SmallGroups.Gap_34.Gap_34_2
import Playground.Geometry.SmallGroups.Gap_35.Gap_35_1
import Playground.Geometry.SmallGroups.Gap_36.Gap_36_14
import Playground.Geometry.SmallGroups.Gap_36.Gap_36_2
import Playground.Geometry.SmallGroups.Gap_36.Gap_36_4
import Playground.Geometry.SmallGroups.Gap_36.Gap_36_5
import Playground.Geometry.SmallGroups.Gap_36.Gap_36_8
import Playground.Geometry.SmallGroups.Gap_37.Gap_37_1
import Playground.Geometry.SmallGroups.Gap_38.Gap_38_1
import Playground.Geometry.SmallGroups.Gap_38.Gap_38_2
import Playground.Geometry.SmallGroups.Gap_39.Gap_39_1
import Playground.Geometry.SmallGroups.Gap_4.Gap_4_1
import Playground.Geometry.SmallGroups.Gap_4.Gap_4_2
import Playground.Geometry.SmallGroups.Gap_40.Gap_40_14
import Playground.Geometry.SmallGroups.Gap_40.Gap_40_2
import Playground.Geometry.SmallGroups.Gap_40.Gap_40_6
import Playground.Geometry.SmallGroups.Gap_40.Gap_40_9
import Playground.Geometry.SmallGroups.Gap_41.Gap_41_1
import Playground.Geometry.SmallGroups.Gap_42.Gap_42_5
import Playground.Geometry.SmallGroups.Gap_42.Gap_42_6
import Playground.Geometry.SmallGroups.Gap_43.Gap_43_1
import Playground.Geometry.SmallGroups.Gap_44.Gap_44_2
import Playground.Geometry.SmallGroups.Gap_44.Gap_44_3
import Playground.Geometry.SmallGroups.Gap_45.Gap_45_1
import Playground.Geometry.SmallGroups.Gap_45.Gap_45_2
import Playground.Geometry.SmallGroups.Gap_46.Gap_46_1
import Playground.Geometry.SmallGroups.Gap_46.Gap_46_2
import Playground.Geometry.SmallGroups.Gap_47.Gap_47_1
import Playground.Geometry.SmallGroups.Gap_48.Gap_48_2
import Playground.Geometry.SmallGroups.Gap_48.Gap_48_20
import Playground.Geometry.SmallGroups.Gap_48.Gap_48_23
import Playground.Geometry.SmallGroups.Gap_48.Gap_48_44
import Playground.Geometry.SmallGroups.Gap_48.Gap_48_52
import Playground.Geometry.SmallGroups.Gap_48.Gap_48_7
import Playground.Geometry.SmallGroups.Gap_49.Gap_49_1
import Playground.Geometry.SmallGroups.Gap_5.Gap_5_1
import Playground.Geometry.SmallGroups.Gap_50.Gap_50_1
import Playground.Geometry.SmallGroups.Gap_50.Gap_50_2
import Playground.Geometry.SmallGroups.Gap_50.Gap_50_5
import Playground.Geometry.SmallGroups.Gap_51.Gap_51_1
import Playground.Geometry.SmallGroups.Gap_52.Gap_52_2
import Playground.Geometry.SmallGroups.Gap_52.Gap_52_4
import Playground.Geometry.SmallGroups.Gap_53.Gap_53_1
import Playground.Geometry.SmallGroups.Gap_54.Gap_54_1
import Playground.Geometry.SmallGroups.Gap_54.Gap_54_15
import Playground.Geometry.SmallGroups.Gap_54.Gap_54_2
import Playground.Geometry.SmallGroups.Gap_54.Gap_54_9
import Playground.Geometry.SmallGroups.Gap_55.Gap_55_2
import Playground.Geometry.SmallGroups.Gap_56.Gap_56_13
import Playground.Geometry.SmallGroups.Gap_56.Gap_56_2
import Playground.Geometry.SmallGroups.Gap_56.Gap_56_5
import Playground.Geometry.SmallGroups.Gap_56.Gap_56_8
import Playground.Geometry.SmallGroups.Gap_57.Gap_57_2
import Playground.Geometry.SmallGroups.Gap_58.Gap_58_1
import Playground.Geometry.SmallGroups.Gap_58.Gap_58_2
import Playground.Geometry.SmallGroups.Gap_59.Gap_59_1
import Playground.Geometry.SmallGroups.Gap_6.Gap_6_1
import Playground.Geometry.SmallGroups.Gap_6.Gap_6_2
import Playground.Geometry.SmallGroups.Gap_60.Gap_60_4
import Playground.Geometry.SmallGroups.Gap_60.Gap_60_5
import Playground.Geometry.SmallGroups.Gap_60.Gap_60_12
import Playground.Geometry.SmallGroups.Gap_60.Gap_60_13
import Playground.Geometry.SmallGroups.Gap_7.Gap_7_1
import Playground.Geometry.SmallGroups.Gap_8.Gap_8_1
import Playground.Geometry.SmallGroups.Gap_8.Gap_8_2
import Playground.Geometry.SmallGroups.Gap_8.Gap_8_3
import Playground.Geometry.SmallGroups.Gap_8.Gap_8_4
import Playground.Geometry.SmallGroups.Gap_8.Gap_8_5
import Playground.Geometry.SmallGroups.Gap_9.Gap_9_1
import Playground.Geometry.SmallGroups.Gap_9.Gap_9_2
