import Mathlib

/-
# Examples from Matt Macauley.
-/

/-
# "A familiar example"
-/

#eval ({0, 1} : Finset (Fin 3))

-- def R :=
abbrev R := (ZMod 3) × (ZMod 3)

abbrev g1 : R := (0, 1)
abbrev g2 : R := (1, 0)

example : Ideal.span { g1, g2 } = ⊤ := by
  suffices _ : ⊤ ≤ Ideal.span {g1, g2} by order
  intro r _
  fin_cases r
  <;> simp only [Nat.reduceAdd, Fin.zero_eta, Fin.isValue]
  <;> rw [Ideal.mem_span_pair]
  <;> decide

private lemma mem_span_g1 (x : R) : x ∈ Ideal.span ({g1} : Set R) ↔ x.1 = 0 := by
  constructor
  · intro hx
    rw [Ideal.mem_span_singleton'] at hx
    obtain ⟨r, rfl⟩ := hx
    grind [Prod.fst_mul, mul_zero]
  · intro hx
    rw [Ideal.mem_span_singleton']
    exact ⟨(0, x.2), by ext <;> simp [g1, hx]⟩

private lemma mem_closure_g1 (x : R) :
    x ∈ NonUnitalSubring.closure ({g1} : Set R) ↔ x.1 = 0 := by
  constructor
  · intro hx
    refine NonUnitalSubring.closure_induction ?_ ?_ ?_ ?_ ?_ hx
    · intro y hy; simp at hy; subst hy; rfl
    · rfl
    · intro a b _ _ ha hb; simp [ha, hb]
    · intro a _ ha; simp [ha]
    · intro a b _ _ ha hb; simp [ha, hb]
  · intro hx
    obtain ⟨a, b⟩ := x
    simp at hx; subst hx
    fin_cases b
    · simp; exact NonUnitalSubring.zero_mem _
    · simp; exact NonUnitalSubring.subset_closure rfl
    · show ((0 : ZMod 3), (2 : ZMod 3)) ∈ _
      have h1 : g1 ∈ NonUnitalSubring.closure ({g1} : Set R) := NonUnitalSubring.subset_closure rfl
      have := NonUnitalSubring.add_mem _ h1 h1
      simp [g1] at this ⊢
      exact this

example : (Ideal.span { g1 }).carrier = NonUnitalSubring.closure { g1 } := by
  ext x; exact (mem_span_g1 x).trans (mem_closure_g1 x).symm

private lemma mem_span_g2 (x : R) : x ∈ Ideal.span ({g2} : Set R) ↔ x.2 = 0 := by
  constructor
  · intro hx
    rw [Ideal.mem_span_singleton'] at hx
    obtain ⟨r, hr⟩ := hx
    have : (r * g2).2 = 0 := by simp [g2]
    rw [← hr]; exact this
  · intro hx
    rw [Ideal.mem_span_singleton']
    exact ⟨(x.1, 0), by ext <;> simp [g2, hx]⟩

private lemma mem_closure_g2 (x : R) :
    x ∈ NonUnitalSubring.closure ({g2} : Set R) ↔ x.2 = 0 := by
  constructor
  · intro hx
    refine NonUnitalSubring.closure_induction ?_ ?_ ?_ ?_ ?_ hx
    · intro y hy; simp at hy; subst hy; rfl
    · rfl
    · intro a b _ _ ha hb; simp [ha, hb]
    · intro a _ ha; simp [ha]
    · intro a b _ _ ha hb; simp [ha, hb]
  · intro hx
    obtain ⟨a, b⟩ := x
    simp at hx; subst hx
    fin_cases a
    · simp; exact NonUnitalSubring.zero_mem _
    · simp; exact NonUnitalSubring.subset_closure rfl
    · show ((2 : ZMod 3), (0 : ZMod 3)) ∈ _
      have h1 : g2 ∈ NonUnitalSubring.closure ({g2} : Set R) := NonUnitalSubring.subset_closure rfl
      have := NonUnitalSubring.add_mem _ h1 h1
      simp [g2] at this ⊢
      exact this

example : (Ideal.span { g2 }).carrier = NonUnitalSubring.closure { g2 } := by
  ext x; exact (mem_span_g2 x).trans (mem_closure_g2 x).symm

private lemma mem_span_g1g2 (x : R) : x ∈ Ideal.span ({g1 + g2} : Set R) := by
  rw [Ideal.mem_span_singleton']
  exact ⟨x, by simp [g1, g2]; ext <;> simp [mul_one]⟩

set_option maxHeartbeats 800000 in
private lemma not_mem_closure_g1g2 :
    ¬ ((1 : ZMod 3), (0 : ZMod 3)) ∈ NonUnitalSubring.closure ({g1 + g2} : Set R) := by
  intro hx
  have : ((1 : ZMod 3), (0 : ZMod 3)).1 = ((1 : ZMod 3), (0 : ZMod 3)).2 := by
    refine NonUnitalSubring.closure_induction ?_ ?_ ?_ ?_ ?_ hx
    · intro y hy; simp [g1, g2] at hy; subst hy; rfl
    · rfl
    · intro a b _ _ ha hb; simp [ha, hb]
    · intro a _ ha; simp [ha]
    · intro a b _ _ ha hb; simp [ha, hb]
  simp at this

example : (Ideal.span { g1 + g2 }).carrier ≠ NonUnitalSubring.closure { g1 + g2 } := by
  intro h
  have h1 : ((1 : ZMod 3), (0 : ZMod 3)) ∈ (Ideal.span { g1 + g2 }).carrier := mem_span_g1g2 _
  rw [h] at h1
  exact not_mem_closure_g1g2 h1

#check Subring.closure


/-

# "The four rings of order 6"

R1 - ZMod 6
R2, R3, R4 hanve the same additive structure, but different multiplicative structures
-/

/-
# R2, which can be defined in the following equivalent ways:
- As the zero ring on the additive group `ZMod 6`
- As the span of `6` in the ring `ZMod 36`
- As a subring of `Z4 + Z9` generated by `(0, 3)` and `(2, 0)`
- As a product...?
-/
structure R2 : Type where
  elem : ZMod 6
deriving DecidableEq

instance R2.instAdd : Add R2 where add a b := { elem := a.elem + b.elem }
lemma R2.add_eq (a b : R2) : a + b = ⟨ a.elem + b.elem ⟩ := rfl

instance R2.instZero : Zero R2 where zero := ⟨0⟩
lemma R2.zero_eq : (0 : R2) = ⟨0⟩ := rfl

instance R2.instNeg : Neg R2 where neg a := ⟨-a.elem⟩
lemma R2.neg_eq (a : R2) : -a = ⟨-a.elem⟩ := rfl

set_option synthInstance.maxHeartbeats 80000

instance R2.instAddCommGroup : AddCommGroup R2 where
  add_assoc a b c := by simp [add_eq]; grind
  zero := ⟨0⟩
  zero_add := by simp [zero_eq, add_eq]
  add_zero := by simp [zero_eq, add_eq]
  nsmul := nsmulRec
  zsmul := zsmulRec
  neg_add_cancel := by simp [neg_eq, add_eq, zero_eq]
  add_comm := by simp [add_eq, add_comm]

instance R2.instMul : Mul R2 where mul _ _ := ⟨ 0 ⟩
lemma R2.mul_eq (a b : R2) : a * b = ⟨ 0 ⟩ := rfl

instance R2.instNonUnitalRing : NonUnitalRing R2 where
  zero_mul := by simp [zero_eq, mul_eq]
  mul_zero := by simp [zero_eq, mul_eq]
  mul_assoc := by simp [mul_eq]
  left_distrib := by simp [mul_eq, zero_eq]
  right_distrib := by simp [mul_eq, zero_eq]

/-
# R3
-/
structure R3 : Type where
  elem : ZMod 6
deriving Fintype, DecidableEq

instance R3.instAdd : Add R3 where add a b := { elem := a.elem + b.elem }
lemma R3.add_eq (a b : R3) : a + b = ⟨ a.elem + b.elem ⟩ := rfl

instance R3.instZero : Zero R3 where zero := ⟨0⟩
lemma R3.zero_eq : (0 : R3) = ⟨0⟩ := rfl

instance R3.instNeg : Neg R3 where neg a := ⟨-a.elem⟩
lemma R3.neg_eq (a : R3) : -a = ⟨-a.elem⟩ := rfl

instance R3.instAddCommGroup : AddCommGroup R3 where
  add_assoc a b c := by simp [add_eq]; grind
  zero := ⟨0⟩
  zero_add := by simp [zero_eq, add_eq]
  add_zero := by simp [zero_eq, add_eq]
  nsmul := nsmulRec
  zsmul := zsmulRec
  neg_add_cancel := by simp [neg_eq, add_eq, zero_eq]
  add_comm := by simp [add_eq, add_comm]

instance R3.instMul : Mul R3 where mul a b := ⟨ 4*a.elem*b.elem ⟩
lemma R3.mul_eq (a b : R3) : a * b = ⟨ 4*a.elem*b.elem ⟩ := rfl

instance R3.instNonUnitalRing : NonUnitalRing R3 where
  zero_mul := by simp [zero_eq, mul_eq]
  mul_zero := by simp [zero_eq, mul_eq]
  mul_assoc := by decide
  left_distrib := by decide
  right_distrib := by decide

/-
# R4
-/
structure R4 : Type where
  elem : ZMod 6
deriving Fintype, DecidableEq

instance R4.instAdd : Add R4 where add a b := { elem := a.elem + b.elem }
lemma R4.add_eq (a b : R4) : a + b = ⟨ a.elem + b.elem ⟩ := rfl

instance R4.instZero : Zero R4 where zero := ⟨0⟩
lemma R4.zero_eq : (0 : R4) = ⟨0⟩ := rfl

instance R4.instNeg : Neg R4 where neg a := ⟨-a.elem⟩
lemma R4.neg_eq (a : R4) : -a = ⟨-a.elem⟩ := rfl

instance R4.instAddCommGroup : AddCommGroup R4 where
  add_assoc a b c := by simp [add_eq]; grind
  zero := ⟨0⟩
  zero_add := by simp [zero_eq, add_eq]
  add_zero := by simp [zero_eq, add_eq]
  nsmul := nsmulRec
  zsmul := zsmulRec
  neg_add_cancel := by simp [neg_eq, add_eq, zero_eq]
  add_comm := by simp [add_eq, add_comm]

instance R4.instMul : Mul R4 where mul a b := ⟨ 3*a.elem*b.elem ⟩
lemma R4.mul_eq (a b : R4) : a * b = ⟨ 3*a.elem*b.elem ⟩ := rfl

instance R4.instNonUnitalRing : NonUnitalRing R4 where
  zero_mul := by simp [zero_eq, mul_eq]
  mul_zero := by simp [zero_eq, mul_eq]
  mul_assoc := by decide
  left_distrib := by decide
  right_distrib := by decide
