import Playground.Basic
import Playground.AoC.Parsers
import Playground.AoC.day1
import Playground.AoC.day2
import Playground.AoC.day2_data
import Playground.AoC.day3
import Playground.AoC.day4
import Playground.AoC.day4_p2
import Playground.AoC.james
import Playground.AoC.test_json
import Playground.Jensen
import Playground.SMOQ2
import Playground.Stern
import Playground.cancellation
-- import Playground.scratch  -- file missing
import Playground.scratch2
import Playground.scratch3
import Playground.test
import Playground.abs
import Playground.Combi1
import Playground.ComplexExamples
import Playground.MyPolynomial
import Playground.NormNumI
import Playground.NormNumI_test
import Playground.Simproc
import Playground.Topology.TopSpace

import Playground.Enumerations
import Playground.PermGeometry
import Playground.BucketProperty
-- import Playground.AristotleTest_aristotle  -- name collision with Combi1
import Playground.a1_aristotle
import Playground.LUMinScaling
import Playground.IrregularityOfDistribution
import Playground.HM_Geometry
import Playground.IdealSumCarrier_aristotle
import Playground.inv_question
import Playground.ListsTest
import Playground.ml_tests
