/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 0e81a920-7298-487b-a5f4-8b9a8c841d7b
-/

/-
Defines G as SL(2, ℤ) and Hn as the congruence subgroup Gamma0(n).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

#check CongruenceSubgroup.Gamma0

/-
Define G as SL(2, ℤ) and Hn as the congruence subgroup Gamma0(n).
-/
abbrev G := Matrix.SpecialLinearGroup (Fin 2) ℤ

def Hn (n : ℕ) : Subgroup G := CongruenceSubgroup.Gamma0 n